// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Permission is the predicate function for permission builders.
type Permission func(*sql.Selector)

// RbacPolicyOutboxEvent is the predicate function for rbacpolicyoutboxevent builders.
type RbacPolicyOutboxEvent func(*sql.Selector)

// RbacPolicyRevision is the predicate function for rbacpolicyrevision builders.
type RbacPolicyRevision func(*sql.Selector)

// RbacPolicyRevisionCounter is the predicate function for rbacpolicyrevisioncounter builders.
type RbacPolicyRevisionCounter func(*sql.Selector)

// RbacUserRoleRevision is the predicate function for rbacuserrolerevision builders.
type RbacUserRoleRevision func(*sql.Selector)

// RbacUserRoleRevisionCounter is the predicate function for rbacuserrolerevisioncounter builders.
type RbacUserRoleRevisionCounter func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// RolePermission is the predicate function for rolepermission builders.
type RolePermission func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UserRole is the predicate function for userrole builders.
type UserRole func(*sql.Selector)
