// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/auth/application (interfaces: UserTokenVersionStore,Metrics)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=redis github.com/aegiscore/user-service/internal/features/auth/application UserTokenVersionStore,Metrics
//

// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserTokenVersionStore is a mock of UserTokenVersionStore interface.
type MockUserTokenVersionStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserTokenVersionStoreMockRecorder
	isgomock struct{}
}

// MockUserTokenVersionStoreMockRecorder is the mock recorder for MockUserTokenVersionStore.
type MockUserTokenVersionStoreMockRecorder struct {
	mock *MockUserTokenVersionStore
}

// NewMockUserTokenVersionStore creates a new mock instance.
func NewMockUserTokenVersionStore(ctrl *gomock.Controller) *MockUserTokenVersionStore {
	mock := &MockUserTokenVersionStore{ctrl: ctrl}
	mock.recorder = &MockUserTokenVersionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTokenVersionStore) EXPECT() *MockUserTokenVersionStoreMockRecorder {
	return m.recorder
}

// GetTokenVersion mocks base method.
func (m *MockUserTokenVersionStore) GetTokenVersion(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenVersion indicates an expected call of GetTokenVersion.
func (mr *MockUserTokenVersionStoreMockRecorder) GetTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenVersion", reflect.TypeOf((*MockUserTokenVersionStore)(nil).GetTokenVersion), ctx, userID)
}

// IncrementTokenVersion mocks base method.
func (m *MockUserTokenVersionStore) IncrementTokenVersion(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementTokenVersion indicates an expected call of IncrementTokenVersion.
func (mr *MockUserTokenVersionStoreMockRecorder) IncrementTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTokenVersion", reflect.TypeOf((*MockUserTokenVersionStore)(nil).IncrementTokenVersion), ctx, userID)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// LoginFailed mocks base method.
func (m *MockMetrics) LoginFailed(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LoginFailed", arg0, arg1)
}

// LoginFailed indicates an expected call of LoginFailed.
func (mr *MockMetricsMockRecorder) LoginFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginFailed", reflect.TypeOf((*MockMetrics)(nil).LoginFailed), arg0, arg1)
}

// LoginSucceeded mocks base method.
func (m *MockMetrics) LoginSucceeded(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LoginSucceeded", arg0)
}

// LoginSucceeded indicates an expected call of LoginSucceeded.
func (mr *MockMetricsMockRecorder) LoginSucceeded(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginSucceeded", reflect.TypeOf((*MockMetrics)(nil).LoginSucceeded), arg0)
}

// LogoutFailed mocks base method.
func (m *MockMetrics) LogoutFailed(arg0 context.Context, arg1, arg2 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogoutFailed", arg0, arg1, arg2)
}

// LogoutFailed indicates an expected call of LogoutFailed.
func (mr *MockMetricsMockRecorder) LogoutFailed(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutFailed", reflect.TypeOf((*MockMetrics)(nil).LogoutFailed), arg0, arg1, arg2)
}

// LogoutSucceeded mocks base method.
func (m *MockMetrics) LogoutSucceeded(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "LogoutSucceeded", arg0, arg1)
}

// LogoutSucceeded indicates an expected call of LogoutSucceeded.
func (mr *MockMetricsMockRecorder) LogoutSucceeded(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogoutSucceeded", reflect.TypeOf((*MockMetrics)(nil).LogoutSucceeded), arg0, arg1)
}

// PasswordChangeRevocationCompensationFailed mocks base method.
func (m *MockMetrics) PasswordChangeRevocationCompensationFailed(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PasswordChangeRevocationCompensationFailed", arg0, arg1)
}

// PasswordChangeRevocationCompensationFailed indicates an expected call of PasswordChangeRevocationCompensationFailed.
func (mr *MockMetricsMockRecorder) PasswordChangeRevocationCompensationFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordChangeRevocationCompensationFailed", reflect.TypeOf((*MockMetrics)(nil).PasswordChangeRevocationCompensationFailed), arg0, arg1)
}

// PasswordChangeRevocationProjectionFailed mocks base method.
func (m *MockMetrics) PasswordChangeRevocationProjectionFailed(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PasswordChangeRevocationProjectionFailed", arg0, arg1)
}

// PasswordChangeRevocationProjectionFailed indicates an expected call of PasswordChangeRevocationProjectionFailed.
func (mr *MockMetricsMockRecorder) PasswordChangeRevocationProjectionFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordChangeRevocationProjectionFailed", reflect.TypeOf((*MockMetrics)(nil).PasswordChangeRevocationProjectionFailed), arg0, arg1)
}

// PasswordChangeSessionConsumeFailed mocks base method.
func (m *MockMetrics) PasswordChangeSessionConsumeFailed(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PasswordChangeSessionConsumeFailed", arg0, arg1)
}

// PasswordChangeSessionConsumeFailed indicates an expected call of PasswordChangeSessionConsumeFailed.
func (mr *MockMetricsMockRecorder) PasswordChangeSessionConsumeFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordChangeSessionConsumeFailed", reflect.TypeOf((*MockMetrics)(nil).PasswordChangeSessionConsumeFailed), arg0, arg1)
}

// PasswordChangeSessionReuseRejected mocks base method.
func (m *MockMetrics) PasswordChangeSessionReuseRejected(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PasswordChangeSessionReuseRejected", arg0)
}

// PasswordChangeSessionReuseRejected indicates an expected call of PasswordChangeSessionReuseRejected.
func (mr *MockMetricsMockRecorder) PasswordChangeSessionReuseRejected(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasswordChangeSessionReuseRejected", reflect.TypeOf((*MockMetrics)(nil).PasswordChangeSessionReuseRejected), arg0)
}

// RefreshFailed mocks base method.
func (m *MockMetrics) RefreshFailed(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshFailed", arg0, arg1)
}

// RefreshFailed indicates an expected call of RefreshFailed.
func (mr *MockMetricsMockRecorder) RefreshFailed(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshFailed", reflect.TypeOf((*MockMetrics)(nil).RefreshFailed), arg0, arg1)
}

// RefreshSucceeded mocks base method.
func (m *MockMetrics) RefreshSucceeded(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RefreshSucceeded", arg0)
}

// RefreshSucceeded indicates an expected call of RefreshSucceeded.
func (mr *MockMetricsMockRecorder) RefreshSucceeded(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshSucceeded", reflect.TypeOf((*MockMetrics)(nil).RefreshSucceeded), arg0)
}

// SessionPurgeSubmitFailed mocks base method.
func (m *MockMetrics) SessionPurgeSubmitFailed(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SessionPurgeSubmitFailed", arg0)
}

// SessionPurgeSubmitFailed indicates an expected call of SessionPurgeSubmitFailed.
func (mr *MockMetricsMockRecorder) SessionPurgeSubmitFailed(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SessionPurgeSubmitFailed", reflect.TypeOf((*MockMetrics)(nil).SessionPurgeSubmitFailed), arg0)
}

// TokenVersionMismatch mocks base method.
func (m *MockMetrics) TokenVersionMismatch(arg0 context.Context, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TokenVersionMismatch", arg0, arg1)
}

// TokenVersionMismatch indicates an expected call of TokenVersionMismatch.
func (mr *MockMetricsMockRecorder) TokenVersionMismatch(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenVersionMismatch", reflect.TypeOf((*MockMetrics)(nil).TokenVersionMismatch), arg0, arg1)
}
