// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/permission/application (interfaces: PermissionStore,PolicyChangeNotifier)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=command github.com/aegiscore/user-service/internal/features/permission/application PermissionStore,PolicyChangeNotifier
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	application "github.com/aegiscore/user-service/internal/features/permission/application"
	domain "github.com/aegiscore/user-service/internal/features/permission/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionStore is a mock of PermissionStore interface.
type MockPermissionStore struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionStoreMockRecorder
	isgomock struct{}
}

// MockPermissionStoreMockRecorder is the mock recorder for MockPermissionStore.
type MockPermissionStoreMockRecorder struct {
	mock *MockPermissionStore
}

// NewMockPermissionStore creates a new mock instance.
func NewMockPermissionStore(ctrl *gomock.Controller) *MockPermissionStore {
	mock := &MockPermissionStore{ctrl: ctrl}
	mock.recorder = &MockPermissionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionStore) EXPECT() *MockPermissionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionStore) Create(ctx context.Context, input application.CreatePermissionInput) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionStoreMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionStore)(nil).Create), ctx, input)
}

// GetByPermissionID mocks base method.
func (m *MockPermissionStore) GetByPermissionID(ctx context.Context, permissionID uuid.UUID) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPermissionID", ctx, permissionID)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPermissionID indicates an expected call of GetByPermissionID.
func (mr *MockPermissionStoreMockRecorder) GetByPermissionID(ctx, permissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPermissionID", reflect.TypeOf((*MockPermissionStore)(nil).GetByPermissionID), ctx, permissionID)
}

// List mocks base method.
func (m *MockPermissionStore) List(ctx context.Context, input application.ListPermissionsInput) ([]domain.Permission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPermissionStoreMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionStore)(nil).List), ctx, input)
}

// ListAll mocks base method.
func (m *MockPermissionStore) ListAll(ctx context.Context) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockPermissionStoreMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockPermissionStore)(nil).ListAll), ctx)
}

// ListEffectiveByUserID mocks base method.
func (m *MockPermissionStore) ListEffectiveByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEffectiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEffectiveByUserID indicates an expected call of ListEffectiveByUserID.
func (mr *MockPermissionStoreMockRecorder) ListEffectiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEffectiveByUserID", reflect.TypeOf((*MockPermissionStore)(nil).ListEffectiveByUserID), ctx, userID)
}

// SetActive mocks base method.
func (m *MockPermissionStore) SetActive(ctx context.Context, permissionID uuid.UUID, active bool) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, permissionID, active)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActive indicates an expected call of SetActive.
func (mr *MockPermissionStoreMockRecorder) SetActive(ctx, permissionID, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockPermissionStore)(nil).SetActive), ctx, permissionID, active)
}

// Update mocks base method.
func (m *MockPermissionStore) Update(ctx context.Context, input application.UpdatePermissionInput) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPermissionStoreMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionStore)(nil).Update), ctx, input)
}

// MockPolicyChangeNotifier is a mock of PolicyChangeNotifier interface.
type MockPolicyChangeNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyChangeNotifierMockRecorder
	isgomock struct{}
}

// MockPolicyChangeNotifierMockRecorder is the mock recorder for MockPolicyChangeNotifier.
type MockPolicyChangeNotifierMockRecorder struct {
	mock *MockPolicyChangeNotifier
}

// NewMockPolicyChangeNotifier creates a new mock instance.
func NewMockPolicyChangeNotifier(ctrl *gomock.Controller) *MockPolicyChangeNotifier {
	mock := &MockPolicyChangeNotifier{ctrl: ctrl}
	mock.recorder = &MockPolicyChangeNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyChangeNotifier) EXPECT() *MockPolicyChangeNotifierMockRecorder {
	return m.recorder
}

// NotifyPolicyChanged mocks base method.
func (m *MockPolicyChangeNotifier) NotifyPolicyChanged(ctx context.Context, change application.PolicyChange) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NotifyPolicyChanged", ctx, change)
	ret0, _ := ret[0].(error)
	return ret0
}

// NotifyPolicyChanged indicates an expected call of NotifyPolicyChanged.
func (mr *MockPolicyChangeNotifierMockRecorder) NotifyPolicyChanged(ctx, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotifyPolicyChanged", reflect.TypeOf((*MockPolicyChangeNotifier)(nil).NotifyPolicyChanged), ctx, change)
}
