// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyoutboxevent"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacuserrolerevision"
	"github.com/google/uuid"
)

// RbacUserRoleRevision is the model entity for the RbacUserRoleRevision schema.
type RbacUserRoleRevision struct {
	config `json:"-"`
	// ID of the ent.
	// 单调递增的 RBAC user-role revision
	ID int64 `json:"id,omitempty"`
	// 创建时间戳毫秒
	CreatedAt int64 `json:"created_at,omitempty"`
	// 触发用户角色缓存失效的稳定原因
	Reason string `json:"reason,omitempty"`
	// 相关外部用户ID
	UserID uuid.UUID `json:"user_id,omitempty"`
	// 相关外部角色ID
	RoleID *uuid.UUID `json:"role_id,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RbacUserRoleRevisionQuery when eager-loading is set.
	Edges        RbacUserRoleRevisionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RbacUserRoleRevisionEdges holds the relations/edges for other nodes in the graph.
type RbacUserRoleRevisionEdges struct {
	// OutboxEvent holds the value of the outbox_event edge.
	OutboxEvent *RbacPolicyOutboxEvent `json:"outbox_event,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// OutboxEventOrErr returns the OutboxEvent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RbacUserRoleRevisionEdges) OutboxEventOrErr() (*RbacPolicyOutboxEvent, error) {
	if e.OutboxEvent != nil {
		return e.OutboxEvent, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: rbacpolicyoutboxevent.Label}
	}
	return nil, &NotLoadedError{edge: "outbox_event"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RbacUserRoleRevision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacuserrolerevision.FieldRoleID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rbacuserrolerevision.FieldID, rbacuserrolerevision.FieldCreatedAt:
			values[i] = new(sql.NullInt64)
		case rbacuserrolerevision.FieldReason:
			values[i] = new(sql.NullString)
		case rbacuserrolerevision.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RbacUserRoleRevision fields.
func (_m *RbacUserRoleRevision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacuserrolerevision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rbacuserrolerevision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case rbacuserrolerevision.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case rbacuserrolerevision.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case rbacuserrolerevision.FieldRoleID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = new(uuid.UUID)
				*_m.RoleID = *value.S.(*uuid.UUID)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RbacUserRoleRevision.
// This includes values selected through modifiers, order, etc.
func (_m *RbacUserRoleRevision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryOutboxEvent queries the "outbox_event" edge of the RbacUserRoleRevision entity.
func (_m *RbacUserRoleRevision) QueryOutboxEvent() *RbacPolicyOutboxEventQuery {
	return NewRbacUserRoleRevisionClient(_m.config).QueryOutboxEvent(_m)
}

// Update returns a builder for updating this RbacUserRoleRevision.
// Note that you need to call RbacUserRoleRevision.Unwrap() before calling this method if this RbacUserRoleRevision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RbacUserRoleRevision) Update() *RbacUserRoleRevisionUpdateOne {
	return NewRbacUserRoleRevisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RbacUserRoleRevision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RbacUserRoleRevision) Unwrap() *RbacUserRoleRevision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RbacUserRoleRevision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RbacUserRoleRevision) String() string {
	var builder strings.Builder
	builder.WriteString("RbacUserRoleRevision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.RoleID; v != nil {
		builder.WriteString("role_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RbacUserRoleRevisions is a parsable slice of RbacUserRoleRevision.
type RbacUserRoleRevisions []*RbacUserRoleRevision
