// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aegiscore/user-service/internal/persistence/ent/predicate"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacuserrolerevisioncounter"
)

// RbacUserRoleRevisionCounterUpdate is the builder for updating RbacUserRoleRevisionCounter entities.
type RbacUserRoleRevisionCounterUpdate struct {
	config
	hooks    []Hook
	mutation *RbacUserRoleRevisionCounterMutation
}

// Where appends a list predicates to the RbacUserRoleRevisionCounterUpdate builder.
func (_u *RbacUserRoleRevisionCounterUpdate) Where(ps ...predicate.RbacUserRoleRevisionCounter) *RbacUserRoleRevisionCounterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetLastRevision sets the "last_revision" field.
func (_u *RbacUserRoleRevisionCounterUpdate) SetLastRevision(v int64) *RbacUserRoleRevisionCounterUpdate {
	_u.mutation.ResetLastRevision()
	_u.mutation.SetLastRevision(v)
	return _u
}

// SetNillableLastRevision sets the "last_revision" field if the given value is not nil.
func (_u *RbacUserRoleRevisionCounterUpdate) SetNillableLastRevision(v *int64) *RbacUserRoleRevisionCounterUpdate {
	if v != nil {
		_u.SetLastRevision(*v)
	}
	return _u
}

// AddLastRevision adds value to the "last_revision" field.
func (_u *RbacUserRoleRevisionCounterUpdate) AddLastRevision(v int64) *RbacUserRoleRevisionCounterUpdate {
	_u.mutation.AddLastRevision(v)
	return _u
}

// Mutation returns the RbacUserRoleRevisionCounterMutation object of the builder.
func (_u *RbacUserRoleRevisionCounterUpdate) Mutation() *RbacUserRoleRevisionCounterMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RbacUserRoleRevisionCounterUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacUserRoleRevisionCounterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RbacUserRoleRevisionCounterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacUserRoleRevisionCounterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacUserRoleRevisionCounterUpdate) check() error {
	if v, ok := _u.mutation.LastRevision(); ok {
		if err := rbacuserrolerevisioncounter.LastRevisionValidator(v); err != nil {
			return &ValidationError{Name: "last_revision", err: fmt.Errorf(`ent: validator failed for field "RbacUserRoleRevisionCounter.last_revision": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacUserRoleRevisionCounterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacuserrolerevisioncounter.Table, rbacuserrolerevisioncounter.Columns, sqlgraph.NewFieldSpec(rbacuserrolerevisioncounter.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastRevision(); ok {
		_spec.SetField(rbacuserrolerevisioncounter.FieldLastRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastRevision(); ok {
		_spec.AddField(rbacuserrolerevisioncounter.FieldLastRevision, field.TypeInt64, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacuserrolerevisioncounter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RbacUserRoleRevisionCounterUpdateOne is the builder for updating a single RbacUserRoleRevisionCounter entity.
type RbacUserRoleRevisionCounterUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RbacUserRoleRevisionCounterMutation
}

// SetLastRevision sets the "last_revision" field.
func (_u *RbacUserRoleRevisionCounterUpdateOne) SetLastRevision(v int64) *RbacUserRoleRevisionCounterUpdateOne {
	_u.mutation.ResetLastRevision()
	_u.mutation.SetLastRevision(v)
	return _u
}

// SetNillableLastRevision sets the "last_revision" field if the given value is not nil.
func (_u *RbacUserRoleRevisionCounterUpdateOne) SetNillableLastRevision(v *int64) *RbacUserRoleRevisionCounterUpdateOne {
	if v != nil {
		_u.SetLastRevision(*v)
	}
	return _u
}

// AddLastRevision adds value to the "last_revision" field.
func (_u *RbacUserRoleRevisionCounterUpdateOne) AddLastRevision(v int64) *RbacUserRoleRevisionCounterUpdateOne {
	_u.mutation.AddLastRevision(v)
	return _u
}

// Mutation returns the RbacUserRoleRevisionCounterMutation object of the builder.
func (_u *RbacUserRoleRevisionCounterUpdateOne) Mutation() *RbacUserRoleRevisionCounterMutation {
	return _u.mutation
}

// Where appends a list predicates to the RbacUserRoleRevisionCounterUpdate builder.
func (_u *RbacUserRoleRevisionCounterUpdateOne) Where(ps ...predicate.RbacUserRoleRevisionCounter) *RbacUserRoleRevisionCounterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RbacUserRoleRevisionCounterUpdateOne) Select(field string, fields ...string) *RbacUserRoleRevisionCounterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RbacUserRoleRevisionCounter entity.
func (_u *RbacUserRoleRevisionCounterUpdateOne) Save(ctx context.Context) (*RbacUserRoleRevisionCounter, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RbacUserRoleRevisionCounterUpdateOne) SaveX(ctx context.Context) *RbacUserRoleRevisionCounter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RbacUserRoleRevisionCounterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RbacUserRoleRevisionCounterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RbacUserRoleRevisionCounterUpdateOne) check() error {
	if v, ok := _u.mutation.LastRevision(); ok {
		if err := rbacuserrolerevisioncounter.LastRevisionValidator(v); err != nil {
			return &ValidationError{Name: "last_revision", err: fmt.Errorf(`ent: validator failed for field "RbacUserRoleRevisionCounter.last_revision": %w`, err)}
		}
	}
	return nil
}

func (_u *RbacUserRoleRevisionCounterUpdateOne) sqlSave(ctx context.Context) (_node *RbacUserRoleRevisionCounter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rbacuserrolerevisioncounter.Table, rbacuserrolerevisioncounter.Columns, sqlgraph.NewFieldSpec(rbacuserrolerevisioncounter.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RbacUserRoleRevisionCounter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rbacuserrolerevisioncounter.FieldID)
		for _, f := range fields {
			if !rbacuserrolerevisioncounter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rbacuserrolerevisioncounter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.LastRevision(); ok {
		_spec.SetField(rbacuserrolerevisioncounter.FieldLastRevision, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedLastRevision(); ok {
		_spec.AddField(rbacuserrolerevisioncounter.FieldLastRevision, field.TypeInt64, value)
	}
	_node = &RbacUserRoleRevisionCounter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rbacuserrolerevisioncounter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
