// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyoutboxevent"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacuserrolerevision"
	"github.com/google/uuid"
)

// RbacUserRoleRevisionCreate is the builder for creating a RbacUserRoleRevision entity.
type RbacUserRoleRevisionCreate struct {
	config
	mutation *RbacUserRoleRevisionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *RbacUserRoleRevisionCreate) SetCreatedAt(v int64) *RbacUserRoleRevisionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RbacUserRoleRevisionCreate) SetNillableCreatedAt(v *int64) *RbacUserRoleRevisionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetReason sets the "reason" field.
func (_c *RbacUserRoleRevisionCreate) SetReason(v string) *RbacUserRoleRevisionCreate {
	_c.mutation.SetReason(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *RbacUserRoleRevisionCreate) SetUserID(v uuid.UUID) *RbacUserRoleRevisionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRoleID sets the "role_id" field.
func (_c *RbacUserRoleRevisionCreate) SetRoleID(v uuid.UUID) *RbacUserRoleRevisionCreate {
	_c.mutation.SetRoleID(v)
	return _c
}

// SetNillableRoleID sets the "role_id" field if the given value is not nil.
func (_c *RbacUserRoleRevisionCreate) SetNillableRoleID(v *uuid.UUID) *RbacUserRoleRevisionCreate {
	if v != nil {
		_c.SetRoleID(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RbacUserRoleRevisionCreate) SetID(v int64) *RbacUserRoleRevisionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetOutboxEventID sets the "outbox_event" edge to the RbacPolicyOutboxEvent entity by ID.
func (_c *RbacUserRoleRevisionCreate) SetOutboxEventID(id int64) *RbacUserRoleRevisionCreate {
	_c.mutation.SetOutboxEventID(id)
	return _c
}

// SetNillableOutboxEventID sets the "outbox_event" edge to the RbacPolicyOutboxEvent entity by ID if the given value is not nil.
func (_c *RbacUserRoleRevisionCreate) SetNillableOutboxEventID(id *int64) *RbacUserRoleRevisionCreate {
	if id != nil {
		_c = _c.SetOutboxEventID(*id)
	}
	return _c
}

// SetOutboxEvent sets the "outbox_event" edge to the RbacPolicyOutboxEvent entity.
func (_c *RbacUserRoleRevisionCreate) SetOutboxEvent(v *RbacPolicyOutboxEvent) *RbacUserRoleRevisionCreate {
	return _c.SetOutboxEventID(v.ID)
}

// Mutation returns the RbacUserRoleRevisionMutation object of the builder.
func (_c *RbacUserRoleRevisionCreate) Mutation() *RbacUserRoleRevisionMutation {
	return _c.mutation
}

// Save creates the RbacUserRoleRevision in the database.
func (_c *RbacUserRoleRevisionCreate) Save(ctx context.Context) (*RbacUserRoleRevision, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RbacUserRoleRevisionCreate) SaveX(ctx context.Context) *RbacUserRoleRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacUserRoleRevisionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacUserRoleRevisionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RbacUserRoleRevisionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rbacuserrolerevision.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RbacUserRoleRevisionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RbacUserRoleRevision.created_at"`)}
	}
	if _, ok := _c.mutation.Reason(); !ok {
		return &ValidationError{Name: "reason", err: errors.New(`ent: missing required field "RbacUserRoleRevision.reason"`)}
	}
	if v, ok := _c.mutation.Reason(); ok {
		if err := rbacuserrolerevision.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "RbacUserRoleRevision.reason": %w`, err)}
		}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "RbacUserRoleRevision.user_id"`)}
	}
	return nil
}

func (_c *RbacUserRoleRevisionCreate) sqlSave(ctx context.Context) (*RbacUserRoleRevision, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RbacUserRoleRevisionCreate) createSpec() (*RbacUserRoleRevision, *sqlgraph.CreateSpec) {
	var (
		_node = &RbacUserRoleRevision{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacuserrolerevision.Table, sqlgraph.NewFieldSpec(rbacuserrolerevision.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rbacuserrolerevision.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Reason(); ok {
		_spec.SetField(rbacuserrolerevision.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(rbacuserrolerevision.FieldUserID, field.TypeUUID, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.RoleID(); ok {
		_spec.SetField(rbacuserrolerevision.FieldRoleID, field.TypeUUID, value)
		_node.RoleID = &value
	}
	if nodes := _c.mutation.OutboxEventIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   rbacuserrolerevision.OutboxEventTable,
			Columns: []string{rbacuserrolerevision.OutboxEventColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rbacpolicyoutboxevent.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RbacUserRoleRevision.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RbacUserRoleRevisionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCreate) OnConflict(opts ...sql.ConflictOption) *RbacUserRoleRevisionUpsertOne {
	_c.conflict = opts
	return &RbacUserRoleRevisionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RbacUserRoleRevision.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCreate) OnConflictColumns(columns ...string) *RbacUserRoleRevisionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RbacUserRoleRevisionUpsertOne{
		create: _c,
	}
}

type (
	// RbacUserRoleRevisionUpsertOne is the builder for "upsert"-ing
	//  one RbacUserRoleRevision node.
	RbacUserRoleRevisionUpsertOne struct {
		create *RbacUserRoleRevisionCreate
	}

	// RbacUserRoleRevisionUpsert is the "OnConflict" setter.
	RbacUserRoleRevisionUpsert struct {
		*sql.UpdateSet
	}
)

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RbacUserRoleRevision.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rbacuserrolerevision.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RbacUserRoleRevisionUpsertOne) UpdateNewValues() *RbacUserRoleRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rbacuserrolerevision.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rbacuserrolerevision.FieldCreatedAt)
		}
		if _, exists := u.create.mutation.Reason(); exists {
			s.SetIgnore(rbacuserrolerevision.FieldReason)
		}
		if _, exists := u.create.mutation.UserID(); exists {
			s.SetIgnore(rbacuserrolerevision.FieldUserID)
		}
		if _, exists := u.create.mutation.RoleID(); exists {
			s.SetIgnore(rbacuserrolerevision.FieldRoleID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RbacUserRoleRevision.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RbacUserRoleRevisionUpsertOne) Ignore() *RbacUserRoleRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RbacUserRoleRevisionUpsertOne) DoNothing() *RbacUserRoleRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RbacUserRoleRevisionCreate.OnConflict
// documentation for more info.
func (u *RbacUserRoleRevisionUpsertOne) Update(set func(*RbacUserRoleRevisionUpsert)) *RbacUserRoleRevisionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RbacUserRoleRevisionUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *RbacUserRoleRevisionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RbacUserRoleRevisionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RbacUserRoleRevisionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RbacUserRoleRevisionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RbacUserRoleRevisionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RbacUserRoleRevisionCreateBulk is the builder for creating many RbacUserRoleRevision entities in bulk.
type RbacUserRoleRevisionCreateBulk struct {
	config
	err      error
	builders []*RbacUserRoleRevisionCreate
	conflict []sql.ConflictOption
}

// Save creates the RbacUserRoleRevision entities in the database.
func (_c *RbacUserRoleRevisionCreateBulk) Save(ctx context.Context) ([]*RbacUserRoleRevision, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RbacUserRoleRevision, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RbacUserRoleRevisionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RbacUserRoleRevisionCreateBulk) SaveX(ctx context.Context) []*RbacUserRoleRevision {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacUserRoleRevisionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacUserRoleRevisionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RbacUserRoleRevision.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RbacUserRoleRevisionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCreateBulk) OnConflict(opts ...sql.ConflictOption) *RbacUserRoleRevisionUpsertBulk {
	_c.conflict = opts
	return &RbacUserRoleRevisionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RbacUserRoleRevision.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCreateBulk) OnConflictColumns(columns ...string) *RbacUserRoleRevisionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RbacUserRoleRevisionUpsertBulk{
		create: _c,
	}
}

// RbacUserRoleRevisionUpsertBulk is the builder for "upsert"-ing
// a bulk of RbacUserRoleRevision nodes.
type RbacUserRoleRevisionUpsertBulk struct {
	create *RbacUserRoleRevisionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RbacUserRoleRevision.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rbacuserrolerevision.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RbacUserRoleRevisionUpsertBulk) UpdateNewValues() *RbacUserRoleRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rbacuserrolerevision.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rbacuserrolerevision.FieldCreatedAt)
			}
			if _, exists := b.mutation.Reason(); exists {
				s.SetIgnore(rbacuserrolerevision.FieldReason)
			}
			if _, exists := b.mutation.UserID(); exists {
				s.SetIgnore(rbacuserrolerevision.FieldUserID)
			}
			if _, exists := b.mutation.RoleID(); exists {
				s.SetIgnore(rbacuserrolerevision.FieldRoleID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RbacUserRoleRevision.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RbacUserRoleRevisionUpsertBulk) Ignore() *RbacUserRoleRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RbacUserRoleRevisionUpsertBulk) DoNothing() *RbacUserRoleRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RbacUserRoleRevisionCreateBulk.OnConflict
// documentation for more info.
func (u *RbacUserRoleRevisionUpsertBulk) Update(set func(*RbacUserRoleRevisionUpsert)) *RbacUserRoleRevisionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RbacUserRoleRevisionUpsert{UpdateSet: update})
	}))
	return u
}

// Exec executes the query.
func (u *RbacUserRoleRevisionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RbacUserRoleRevisionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RbacUserRoleRevisionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RbacUserRoleRevisionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
