// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyrevisioncounter"
)

// RbacPolicyRevisionCounter is the model entity for the RbacPolicyRevisionCounter schema.
type RbacPolicyRevisionCounter struct {
	config `json:"-"`
	// ID of the ent.
	// 固定 RBAC policy revision counter ID
	ID int64 `json:"id,omitempty"`
	// 最近已分配的 RBAC policy revision
	LastRevision int64 `json:"last_revision,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RbacPolicyRevisionCounter) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacpolicyrevisioncounter.FieldID, rbacpolicyrevisioncounter.FieldLastRevision:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RbacPolicyRevisionCounter fields.
func (_m *RbacPolicyRevisionCounter) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacpolicyrevisioncounter.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rbacpolicyrevisioncounter.FieldLastRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_revision", values[i])
			} else if value.Valid {
				_m.LastRevision = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RbacPolicyRevisionCounter.
// This includes values selected through modifiers, order, etc.
func (_m *RbacPolicyRevisionCounter) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RbacPolicyRevisionCounter.
// Note that you need to call RbacPolicyRevisionCounter.Unwrap() before calling this method if this RbacPolicyRevisionCounter
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RbacPolicyRevisionCounter) Update() *RbacPolicyRevisionCounterUpdateOne {
	return NewRbacPolicyRevisionCounterClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RbacPolicyRevisionCounter entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RbacPolicyRevisionCounter) Unwrap() *RbacPolicyRevisionCounter {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RbacPolicyRevisionCounter is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RbacPolicyRevisionCounter) String() string {
	var builder strings.Builder
	builder.WriteString("RbacPolicyRevisionCounter(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("last_revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.LastRevision))
	builder.WriteByte(')')
	return builder.String()
}

// RbacPolicyRevisionCounters is a parsable slice of RbacPolicyRevisionCounter.
type RbacPolicyRevisionCounters []*RbacPolicyRevisionCounter
