// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacuserrolerevisioncounter"
)

// RbacUserRoleRevisionCounterCreate is the builder for creating a RbacUserRoleRevisionCounter entity.
type RbacUserRoleRevisionCounterCreate struct {
	config
	mutation *RbacUserRoleRevisionCounterMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetLastRevision sets the "last_revision" field.
func (_c *RbacUserRoleRevisionCounterCreate) SetLastRevision(v int64) *RbacUserRoleRevisionCounterCreate {
	_c.mutation.SetLastRevision(v)
	return _c
}

// SetNillableLastRevision sets the "last_revision" field if the given value is not nil.
func (_c *RbacUserRoleRevisionCounterCreate) SetNillableLastRevision(v *int64) *RbacUserRoleRevisionCounterCreate {
	if v != nil {
		_c.SetLastRevision(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *RbacUserRoleRevisionCounterCreate) SetID(v int64) *RbacUserRoleRevisionCounterCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the RbacUserRoleRevisionCounterMutation object of the builder.
func (_c *RbacUserRoleRevisionCounterCreate) Mutation() *RbacUserRoleRevisionCounterMutation {
	return _c.mutation
}

// Save creates the RbacUserRoleRevisionCounter in the database.
func (_c *RbacUserRoleRevisionCounterCreate) Save(ctx context.Context) (*RbacUserRoleRevisionCounter, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RbacUserRoleRevisionCounterCreate) SaveX(ctx context.Context) *RbacUserRoleRevisionCounter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacUserRoleRevisionCounterCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacUserRoleRevisionCounterCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RbacUserRoleRevisionCounterCreate) defaults() {
	if _, ok := _c.mutation.LastRevision(); !ok {
		v := rbacuserrolerevisioncounter.DefaultLastRevision
		_c.mutation.SetLastRevision(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RbacUserRoleRevisionCounterCreate) check() error {
	if _, ok := _c.mutation.LastRevision(); !ok {
		return &ValidationError{Name: "last_revision", err: errors.New(`ent: missing required field "RbacUserRoleRevisionCounter.last_revision"`)}
	}
	if v, ok := _c.mutation.LastRevision(); ok {
		if err := rbacuserrolerevisioncounter.LastRevisionValidator(v); err != nil {
			return &ValidationError{Name: "last_revision", err: fmt.Errorf(`ent: validator failed for field "RbacUserRoleRevisionCounter.last_revision": %w`, err)}
		}
	}
	return nil
}

func (_c *RbacUserRoleRevisionCounterCreate) sqlSave(ctx context.Context) (*RbacUserRoleRevisionCounter, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RbacUserRoleRevisionCounterCreate) createSpec() (*RbacUserRoleRevisionCounter, *sqlgraph.CreateSpec) {
	var (
		_node = &RbacUserRoleRevisionCounter{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rbacuserrolerevisioncounter.Table, sqlgraph.NewFieldSpec(rbacuserrolerevisioncounter.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.LastRevision(); ok {
		_spec.SetField(rbacuserrolerevisioncounter.FieldLastRevision, field.TypeInt64, value)
		_node.LastRevision = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RbacUserRoleRevisionCounter.Create().
//		SetLastRevision(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RbacUserRoleRevisionCounterUpsert) {
//			SetLastRevision(v+v).
//		}).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCounterCreate) OnConflict(opts ...sql.ConflictOption) *RbacUserRoleRevisionCounterUpsertOne {
	_c.conflict = opts
	return &RbacUserRoleRevisionCounterUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RbacUserRoleRevisionCounter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCounterCreate) OnConflictColumns(columns ...string) *RbacUserRoleRevisionCounterUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RbacUserRoleRevisionCounterUpsertOne{
		create: _c,
	}
}

type (
	// RbacUserRoleRevisionCounterUpsertOne is the builder for "upsert"-ing
	//  one RbacUserRoleRevisionCounter node.
	RbacUserRoleRevisionCounterUpsertOne struct {
		create *RbacUserRoleRevisionCounterCreate
	}

	// RbacUserRoleRevisionCounterUpsert is the "OnConflict" setter.
	RbacUserRoleRevisionCounterUpsert struct {
		*sql.UpdateSet
	}
)

// SetLastRevision sets the "last_revision" field.
func (u *RbacUserRoleRevisionCounterUpsert) SetLastRevision(v int64) *RbacUserRoleRevisionCounterUpsert {
	u.Set(rbacuserrolerevisioncounter.FieldLastRevision, v)
	return u
}

// UpdateLastRevision sets the "last_revision" field to the value that was provided on create.
func (u *RbacUserRoleRevisionCounterUpsert) UpdateLastRevision() *RbacUserRoleRevisionCounterUpsert {
	u.SetExcluded(rbacuserrolerevisioncounter.FieldLastRevision)
	return u
}

// AddLastRevision adds v to the "last_revision" field.
func (u *RbacUserRoleRevisionCounterUpsert) AddLastRevision(v int64) *RbacUserRoleRevisionCounterUpsert {
	u.Add(rbacuserrolerevisioncounter.FieldLastRevision, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.RbacUserRoleRevisionCounter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rbacuserrolerevisioncounter.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RbacUserRoleRevisionCounterUpsertOne) UpdateNewValues() *RbacUserRoleRevisionCounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(rbacuserrolerevisioncounter.FieldID)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RbacUserRoleRevisionCounter.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RbacUserRoleRevisionCounterUpsertOne) Ignore() *RbacUserRoleRevisionCounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RbacUserRoleRevisionCounterUpsertOne) DoNothing() *RbacUserRoleRevisionCounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RbacUserRoleRevisionCounterCreate.OnConflict
// documentation for more info.
func (u *RbacUserRoleRevisionCounterUpsertOne) Update(set func(*RbacUserRoleRevisionCounterUpsert)) *RbacUserRoleRevisionCounterUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RbacUserRoleRevisionCounterUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastRevision sets the "last_revision" field.
func (u *RbacUserRoleRevisionCounterUpsertOne) SetLastRevision(v int64) *RbacUserRoleRevisionCounterUpsertOne {
	return u.Update(func(s *RbacUserRoleRevisionCounterUpsert) {
		s.SetLastRevision(v)
	})
}

// AddLastRevision adds v to the "last_revision" field.
func (u *RbacUserRoleRevisionCounterUpsertOne) AddLastRevision(v int64) *RbacUserRoleRevisionCounterUpsertOne {
	return u.Update(func(s *RbacUserRoleRevisionCounterUpsert) {
		s.AddLastRevision(v)
	})
}

// UpdateLastRevision sets the "last_revision" field to the value that was provided on create.
func (u *RbacUserRoleRevisionCounterUpsertOne) UpdateLastRevision() *RbacUserRoleRevisionCounterUpsertOne {
	return u.Update(func(s *RbacUserRoleRevisionCounterUpsert) {
		s.UpdateLastRevision()
	})
}

// Exec executes the query.
func (u *RbacUserRoleRevisionCounterUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RbacUserRoleRevisionCounterCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RbacUserRoleRevisionCounterUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RbacUserRoleRevisionCounterUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RbacUserRoleRevisionCounterUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RbacUserRoleRevisionCounterCreateBulk is the builder for creating many RbacUserRoleRevisionCounter entities in bulk.
type RbacUserRoleRevisionCounterCreateBulk struct {
	config
	err      error
	builders []*RbacUserRoleRevisionCounterCreate
	conflict []sql.ConflictOption
}

// Save creates the RbacUserRoleRevisionCounter entities in the database.
func (_c *RbacUserRoleRevisionCounterCreateBulk) Save(ctx context.Context) ([]*RbacUserRoleRevisionCounter, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RbacUserRoleRevisionCounter, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RbacUserRoleRevisionCounterMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RbacUserRoleRevisionCounterCreateBulk) SaveX(ctx context.Context) []*RbacUserRoleRevisionCounter {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RbacUserRoleRevisionCounterCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RbacUserRoleRevisionCounterCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RbacUserRoleRevisionCounter.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RbacUserRoleRevisionCounterUpsert) {
//			SetLastRevision(v+v).
//		}).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCounterCreateBulk) OnConflict(opts ...sql.ConflictOption) *RbacUserRoleRevisionCounterUpsertBulk {
	_c.conflict = opts
	return &RbacUserRoleRevisionCounterUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RbacUserRoleRevisionCounter.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RbacUserRoleRevisionCounterCreateBulk) OnConflictColumns(columns ...string) *RbacUserRoleRevisionCounterUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RbacUserRoleRevisionCounterUpsertBulk{
		create: _c,
	}
}

// RbacUserRoleRevisionCounterUpsertBulk is the builder for "upsert"-ing
// a bulk of RbacUserRoleRevisionCounter nodes.
type RbacUserRoleRevisionCounterUpsertBulk struct {
	create *RbacUserRoleRevisionCounterCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RbacUserRoleRevisionCounter.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(rbacuserrolerevisioncounter.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *RbacUserRoleRevisionCounterUpsertBulk) UpdateNewValues() *RbacUserRoleRevisionCounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(rbacuserrolerevisioncounter.FieldID)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RbacUserRoleRevisionCounter.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RbacUserRoleRevisionCounterUpsertBulk) Ignore() *RbacUserRoleRevisionCounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RbacUserRoleRevisionCounterUpsertBulk) DoNothing() *RbacUserRoleRevisionCounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RbacUserRoleRevisionCounterCreateBulk.OnConflict
// documentation for more info.
func (u *RbacUserRoleRevisionCounterUpsertBulk) Update(set func(*RbacUserRoleRevisionCounterUpsert)) *RbacUserRoleRevisionCounterUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RbacUserRoleRevisionCounterUpsert{UpdateSet: update})
	}))
	return u
}

// SetLastRevision sets the "last_revision" field.
func (u *RbacUserRoleRevisionCounterUpsertBulk) SetLastRevision(v int64) *RbacUserRoleRevisionCounterUpsertBulk {
	return u.Update(func(s *RbacUserRoleRevisionCounterUpsert) {
		s.SetLastRevision(v)
	})
}

// AddLastRevision adds v to the "last_revision" field.
func (u *RbacUserRoleRevisionCounterUpsertBulk) AddLastRevision(v int64) *RbacUserRoleRevisionCounterUpsertBulk {
	return u.Update(func(s *RbacUserRoleRevisionCounterUpsert) {
		s.AddLastRevision(v)
	})
}

// UpdateLastRevision sets the "last_revision" field to the value that was provided on create.
func (u *RbacUserRoleRevisionCounterUpsertBulk) UpdateLastRevision() *RbacUserRoleRevisionCounterUpsertBulk {
	return u.Update(func(s *RbacUserRoleRevisionCounterUpsert) {
		s.UpdateLastRevision()
	})
}

// Exec executes the query.
func (u *RbacUserRoleRevisionCounterUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RbacUserRoleRevisionCounterCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RbacUserRoleRevisionCounterCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RbacUserRoleRevisionCounterUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
