// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aegiscore/user-service/internal/persistence/ent/predicate"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyoutboxevent"
)

// RbacPolicyOutboxEventDelete is the builder for deleting a RbacPolicyOutboxEvent entity.
type RbacPolicyOutboxEventDelete struct {
	config
	hooks    []Hook
	mutation *RbacPolicyOutboxEventMutation
}

// Where appends a list predicates to the RbacPolicyOutboxEventDelete builder.
func (_d *RbacPolicyOutboxEventDelete) Where(ps ...predicate.RbacPolicyOutboxEvent) *RbacPolicyOutboxEventDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RbacPolicyOutboxEventDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RbacPolicyOutboxEventDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RbacPolicyOutboxEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rbacpolicyoutboxevent.Table, sqlgraph.NewFieldSpec(rbacpolicyoutboxevent.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RbacPolicyOutboxEventDeleteOne is the builder for deleting a single RbacPolicyOutboxEvent entity.
type RbacPolicyOutboxEventDeleteOne struct {
	_d *RbacPolicyOutboxEventDelete
}

// Where appends a list predicates to the RbacPolicyOutboxEventDelete builder.
func (_d *RbacPolicyOutboxEventDeleteOne) Where(ps ...predicate.RbacPolicyOutboxEvent) *RbacPolicyOutboxEventDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RbacPolicyOutboxEventDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rbacpolicyoutboxevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RbacPolicyOutboxEventDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
