// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aegiscore/user-service/internal/persistence/ent/predicate"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyrevision"
)

// RbacPolicyRevisionDelete is the builder for deleting a RbacPolicyRevision entity.
type RbacPolicyRevisionDelete struct {
	config
	hooks    []Hook
	mutation *RbacPolicyRevisionMutation
}

// Where appends a list predicates to the RbacPolicyRevisionDelete builder.
func (_d *RbacPolicyRevisionDelete) Where(ps ...predicate.RbacPolicyRevision) *RbacPolicyRevisionDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RbacPolicyRevisionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RbacPolicyRevisionDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RbacPolicyRevisionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(rbacpolicyrevision.Table, sqlgraph.NewFieldSpec(rbacpolicyrevision.FieldID, field.TypeInt64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RbacPolicyRevisionDeleteOne is the builder for deleting a single RbacPolicyRevision entity.
type RbacPolicyRevisionDeleteOne struct {
	_d *RbacPolicyRevisionDelete
}

// Where appends a list predicates to the RbacPolicyRevisionDelete builder.
func (_d *RbacPolicyRevisionDeleteOne) Where(ps ...predicate.RbacPolicyRevision) *RbacPolicyRevisionDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RbacPolicyRevisionDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{rbacpolicyrevision.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RbacPolicyRevisionDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
