// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyoutboxevent"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyrevision"
	"github.com/google/uuid"
)

// RbacPolicyOutboxEvent is the model entity for the RbacPolicyOutboxEvent schema.
type RbacPolicyOutboxEvent struct {
	config `json:"-"`
	// ID of the ent.
	// RBAC policy outbox 内部ID
	ID int64 `json:"id,omitempty"`
	// 稳定 outbox event ID
	EventID uuid.UUID `json:"event_id,omitempty"`
	// 关联的 RBAC policy revision
	Revision int64 `json:"revision,omitempty"`
	// 事件类型
	Kind string `json:"kind,omitempty"`
	// 触发 policy 变更的稳定原因
	Reason string `json:"reason,omitempty"`
	// 相关外部角色ID
	RoleID *uuid.UUID `json:"role_id,omitempty"`
	// 相关外部用户ID
	UserID *uuid.UUID `json:"user_id,omitempty"`
	// 相关外部权限ID
	PermissionID *uuid.UUID `json:"permission_id,omitempty"`
	// 投递状态
	Status string `json:"status,omitempty"`
	// 投递尝试次数
	AttemptCount int `json:"attempt_count,omitempty"`
	// 下次允许尝试的时间戳毫秒
	NextAttemptAt int64 `json:"next_attempt_at,omitempty"`
	// 最近一次投递错误
	LastError *string `json:"last_error,omitempty"`
	// 稳定投递幂等键
	IdempotencyKey string `json:"idempotency_key,omitempty"`
	// 创建时间戳毫秒
	CreatedAt int64 `json:"created_at,omitempty"`
	// 更新时间戳毫秒
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// 投递完成时间戳毫秒
	DeliveredAt *int64 `json:"delivered_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RbacPolicyOutboxEventQuery when eager-loading is set.
	Edges        RbacPolicyOutboxEventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// RbacPolicyOutboxEventEdges holds the relations/edges for other nodes in the graph.
type RbacPolicyOutboxEventEdges struct {
	// PolicyRevision holds the value of the policy_revision edge.
	PolicyRevision *RbacPolicyRevision `json:"policy_revision,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PolicyRevisionOrErr returns the PolicyRevision value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RbacPolicyOutboxEventEdges) PolicyRevisionOrErr() (*RbacPolicyRevision, error) {
	if e.PolicyRevision != nil {
		return e.PolicyRevision, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: rbacpolicyrevision.Label}
	}
	return nil, &NotLoadedError{edge: "policy_revision"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RbacPolicyOutboxEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rbacpolicyoutboxevent.FieldRoleID, rbacpolicyoutboxevent.FieldUserID, rbacpolicyoutboxevent.FieldPermissionID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case rbacpolicyoutboxevent.FieldID, rbacpolicyoutboxevent.FieldRevision, rbacpolicyoutboxevent.FieldAttemptCount, rbacpolicyoutboxevent.FieldNextAttemptAt, rbacpolicyoutboxevent.FieldCreatedAt, rbacpolicyoutboxevent.FieldUpdatedAt, rbacpolicyoutboxevent.FieldDeliveredAt:
			values[i] = new(sql.NullInt64)
		case rbacpolicyoutboxevent.FieldKind, rbacpolicyoutboxevent.FieldReason, rbacpolicyoutboxevent.FieldStatus, rbacpolicyoutboxevent.FieldLastError, rbacpolicyoutboxevent.FieldIdempotencyKey:
			values[i] = new(sql.NullString)
		case rbacpolicyoutboxevent.FieldEventID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RbacPolicyOutboxEvent fields.
func (_m *RbacPolicyOutboxEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rbacpolicyoutboxevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rbacpolicyoutboxevent.FieldEventID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field event_id", values[i])
			} else if value != nil {
				_m.EventID = *value
			}
		case rbacpolicyoutboxevent.FieldRevision:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field revision", values[i])
			} else if value.Valid {
				_m.Revision = value.Int64
			}
		case rbacpolicyoutboxevent.FieldKind:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = value.String
			}
		case rbacpolicyoutboxevent.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = value.String
			}
		case rbacpolicyoutboxevent.FieldRoleID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field role_id", values[i])
			} else if value.Valid {
				_m.RoleID = new(uuid.UUID)
				*_m.RoleID = *value.S.(*uuid.UUID)
			}
		case rbacpolicyoutboxevent.FieldUserID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = new(uuid.UUID)
				*_m.UserID = *value.S.(*uuid.UUID)
			}
		case rbacpolicyoutboxevent.FieldPermissionID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field permission_id", values[i])
			} else if value.Valid {
				_m.PermissionID = new(uuid.UUID)
				*_m.PermissionID = *value.S.(*uuid.UUID)
			}
		case rbacpolicyoutboxevent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case rbacpolicyoutboxevent.FieldAttemptCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_count", values[i])
			} else if value.Valid {
				_m.AttemptCount = int(value.Int64)
			}
		case rbacpolicyoutboxevent.FieldNextAttemptAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field next_attempt_at", values[i])
			} else if value.Valid {
				_m.NextAttemptAt = value.Int64
			}
		case rbacpolicyoutboxevent.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = new(string)
				*_m.LastError = value.String
			}
		case rbacpolicyoutboxevent.FieldIdempotencyKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field idempotency_key", values[i])
			} else if value.Valid {
				_m.IdempotencyKey = value.String
			}
		case rbacpolicyoutboxevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Int64
			}
		case rbacpolicyoutboxevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Int64
			}
		case rbacpolicyoutboxevent.FieldDeliveredAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field delivered_at", values[i])
			} else if value.Valid {
				_m.DeliveredAt = new(int64)
				*_m.DeliveredAt = value.Int64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RbacPolicyOutboxEvent.
// This includes values selected through modifiers, order, etc.
func (_m *RbacPolicyOutboxEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPolicyRevision queries the "policy_revision" edge of the RbacPolicyOutboxEvent entity.
func (_m *RbacPolicyOutboxEvent) QueryPolicyRevision() *RbacPolicyRevisionQuery {
	return NewRbacPolicyOutboxEventClient(_m.config).QueryPolicyRevision(_m)
}

// Update returns a builder for updating this RbacPolicyOutboxEvent.
// Note that you need to call RbacPolicyOutboxEvent.Unwrap() before calling this method if this RbacPolicyOutboxEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RbacPolicyOutboxEvent) Update() *RbacPolicyOutboxEventUpdateOne {
	return NewRbacPolicyOutboxEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RbacPolicyOutboxEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RbacPolicyOutboxEvent) Unwrap() *RbacPolicyOutboxEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RbacPolicyOutboxEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RbacPolicyOutboxEvent) String() string {
	var builder strings.Builder
	builder.WriteString("RbacPolicyOutboxEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("event_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.EventID))
	builder.WriteString(", ")
	builder.WriteString("revision=")
	builder.WriteString(fmt.Sprintf("%v", _m.Revision))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(_m.Kind)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(_m.Reason)
	builder.WriteString(", ")
	if v := _m.RoleID; v != nil {
		builder.WriteString("role_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.UserID; v != nil {
		builder.WriteString("user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.PermissionID; v != nil {
		builder.WriteString("permission_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("attempt_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptCount))
	builder.WriteString(", ")
	builder.WriteString("next_attempt_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.NextAttemptAt))
	builder.WriteString(", ")
	if v := _m.LastError; v != nil {
		builder.WriteString("last_error=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("idempotency_key=")
	builder.WriteString(_m.IdempotencyKey)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.UpdatedAt))
	builder.WriteString(", ")
	if v := _m.DeliveredAt; v != nil {
		builder.WriteString("delivered_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RbacPolicyOutboxEvents is a parsable slice of RbacPolicyOutboxEvent.
type RbacPolicyOutboxEvents []*RbacPolicyOutboxEvent
