// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/aegiscore/user-service/internal/persistence/ent/permission"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyoutboxevent"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyrevision"
	"github.com/aegiscore/user-service/internal/persistence/ent/rbacpolicyrevisioncounter"
	"github.com/aegiscore/user-service/internal/persistence/ent/role"
	"github.com/aegiscore/user-service/internal/persistence/ent/rolepermission"
	"github.com/aegiscore/user-service/internal/persistence/ent/schema"
	"github.com/aegiscore/user-service/internal/persistence/ent/user"
	"github.com/aegiscore/user-service/internal/persistence/ent/userrole"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	permissionFields := schema.Permission{}.Fields()
	_ = permissionFields
	// permissionDescName is the schema descriptor for name field.
	permissionDescName := permissionFields[2].Descriptor()
	// permission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	permission.NameValidator = func() func(string) error {
		validators := permissionDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescDescription is the schema descriptor for description field.
	permissionDescDescription := permissionFields[3].Descriptor()
	// permission.DefaultDescription holds the default value on creation for the description field.
	permission.DefaultDescription = permissionDescDescription.Default.(string)
	// permission.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	permission.DescriptionValidator = permissionDescDescription.Validators[0].(func(string) error)
	// permissionDescModule is the schema descriptor for module field.
	permissionDescModule := permissionFields[4].Descriptor()
	// permission.ModuleValidator is a validator for the "module" field. It is called by the builders before save.
	permission.ModuleValidator = func() func(string) error {
		validators := permissionDescModule.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(module string) error {
			for _, fn := range fns {
				if err := fn(module); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescHTTPMethod is the schema descriptor for http_method field.
	permissionDescHTTPMethod := permissionFields[5].Descriptor()
	// permission.HTTPMethodValidator is a validator for the "http_method" field. It is called by the builders before save.
	permission.HTTPMethodValidator = func() func(string) error {
		validators := permissionDescHTTPMethod.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(http_method string) error {
			for _, fn := range fns {
				if err := fn(http_method); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescPathTemplate is the schema descriptor for path_template field.
	permissionDescPathTemplate := permissionFields[6].Descriptor()
	// permission.PathTemplateValidator is a validator for the "path_template" field. It is called by the builders before save.
	permission.PathTemplateValidator = func() func(string) error {
		validators := permissionDescPathTemplate.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(path_template string) error {
			for _, fn := range fns {
				if err := fn(path_template); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// permissionDescCreatedAt is the schema descriptor for created_at field.
	permissionDescCreatedAt := permissionFields[7].Descriptor()
	// permission.DefaultCreatedAt holds the default value on creation for the created_at field.
	permission.DefaultCreatedAt = permissionDescCreatedAt.Default.(func() int64)
	// permissionDescUpdatedAt is the schema descriptor for updated_at field.
	permissionDescUpdatedAt := permissionFields[8].Descriptor()
	// permission.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	permission.DefaultUpdatedAt = permissionDescUpdatedAt.Default.(func() int64)
	// permission.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	permission.UpdateDefaultUpdatedAt = permissionDescUpdatedAt.UpdateDefault.(func() int64)
	rbacpolicyoutboxeventFields := schema.RbacPolicyOutboxEvent{}.Fields()
	_ = rbacpolicyoutboxeventFields
	// rbacpolicyoutboxeventDescKind is the schema descriptor for kind field.
	rbacpolicyoutboxeventDescKind := rbacpolicyoutboxeventFields[3].Descriptor()
	// rbacpolicyoutboxevent.KindValidator is a validator for the "kind" field. It is called by the builders before save.
	rbacpolicyoutboxevent.KindValidator = func() func(string) error {
		validators := rbacpolicyoutboxeventDescKind.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
			validators[2].(func(string) error),
		}
		return func(kind string) error {
			for _, fn := range fns {
				if err := fn(kind); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// rbacpolicyoutboxeventDescReason is the schema descriptor for reason field.
	rbacpolicyoutboxeventDescReason := rbacpolicyoutboxeventFields[4].Descriptor()
	// rbacpolicyoutboxevent.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	rbacpolicyoutboxevent.ReasonValidator = func() func(string) error {
		validators := rbacpolicyoutboxeventDescReason.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(reason string) error {
			for _, fn := range fns {
				if err := fn(reason); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// rbacpolicyoutboxeventDescStatus is the schema descriptor for status field.
	rbacpolicyoutboxeventDescStatus := rbacpolicyoutboxeventFields[8].Descriptor()
	// rbacpolicyoutboxevent.DefaultStatus holds the default value on creation for the status field.
	rbacpolicyoutboxevent.DefaultStatus = rbacpolicyoutboxeventDescStatus.Default.(string)
	// rbacpolicyoutboxevent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	rbacpolicyoutboxevent.StatusValidator = func() func(string) error {
		validators := rbacpolicyoutboxeventDescStatus.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(status string) error {
			for _, fn := range fns {
				if err := fn(status); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// rbacpolicyoutboxeventDescAttemptCount is the schema descriptor for attempt_count field.
	rbacpolicyoutboxeventDescAttemptCount := rbacpolicyoutboxeventFields[9].Descriptor()
	// rbacpolicyoutboxevent.DefaultAttemptCount holds the default value on creation for the attempt_count field.
	rbacpolicyoutboxevent.DefaultAttemptCount = rbacpolicyoutboxeventDescAttemptCount.Default.(int)
	// rbacpolicyoutboxevent.AttemptCountValidator is a validator for the "attempt_count" field. It is called by the builders before save.
	rbacpolicyoutboxevent.AttemptCountValidator = rbacpolicyoutboxeventDescAttemptCount.Validators[0].(func(int) error)
	// rbacpolicyoutboxeventDescNextAttemptAt is the schema descriptor for next_attempt_at field.
	rbacpolicyoutboxeventDescNextAttemptAt := rbacpolicyoutboxeventFields[10].Descriptor()
	// rbacpolicyoutboxevent.DefaultNextAttemptAt holds the default value on creation for the next_attempt_at field.
	rbacpolicyoutboxevent.DefaultNextAttemptAt = rbacpolicyoutboxeventDescNextAttemptAt.Default.(func() int64)
	// rbacpolicyoutboxeventDescLastError is the schema descriptor for last_error field.
	rbacpolicyoutboxeventDescLastError := rbacpolicyoutboxeventFields[11].Descriptor()
	// rbacpolicyoutboxevent.LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	rbacpolicyoutboxevent.LastErrorValidator = rbacpolicyoutboxeventDescLastError.Validators[0].(func(string) error)
	// rbacpolicyoutboxeventDescIdempotencyKey is the schema descriptor for idempotency_key field.
	rbacpolicyoutboxeventDescIdempotencyKey := rbacpolicyoutboxeventFields[14].Descriptor()
	// rbacpolicyoutboxevent.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	rbacpolicyoutboxevent.IdempotencyKeyValidator = func() func(string) error {
		validators := rbacpolicyoutboxeventDescIdempotencyKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(idempotency_key string) error {
			for _, fn := range fns {
				if err := fn(idempotency_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// rbacpolicyoutboxeventDescCreatedAt is the schema descriptor for created_at field.
	rbacpolicyoutboxeventDescCreatedAt := rbacpolicyoutboxeventFields[15].Descriptor()
	// rbacpolicyoutboxevent.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacpolicyoutboxevent.DefaultCreatedAt = rbacpolicyoutboxeventDescCreatedAt.Default.(func() int64)
	// rbacpolicyoutboxeventDescUpdatedAt is the schema descriptor for updated_at field.
	rbacpolicyoutboxeventDescUpdatedAt := rbacpolicyoutboxeventFields[16].Descriptor()
	// rbacpolicyoutboxevent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	rbacpolicyoutboxevent.DefaultUpdatedAt = rbacpolicyoutboxeventDescUpdatedAt.Default.(func() int64)
	// rbacpolicyoutboxevent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	rbacpolicyoutboxevent.UpdateDefaultUpdatedAt = rbacpolicyoutboxeventDescUpdatedAt.UpdateDefault.(func() int64)
	rbacpolicyrevisionFields := schema.RbacPolicyRevision{}.Fields()
	_ = rbacpolicyrevisionFields
	// rbacpolicyrevisionDescReason is the schema descriptor for reason field.
	rbacpolicyrevisionDescReason := rbacpolicyrevisionFields[1].Descriptor()
	// rbacpolicyrevision.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	rbacpolicyrevision.ReasonValidator = func() func(string) error {
		validators := rbacpolicyrevisionDescReason.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(reason string) error {
			for _, fn := range fns {
				if err := fn(reason); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// rbacpolicyrevisionDescCreatedAt is the schema descriptor for created_at field.
	rbacpolicyrevisionDescCreatedAt := rbacpolicyrevisionFields[5].Descriptor()
	// rbacpolicyrevision.DefaultCreatedAt holds the default value on creation for the created_at field.
	rbacpolicyrevision.DefaultCreatedAt = rbacpolicyrevisionDescCreatedAt.Default.(func() int64)
	rbacpolicyrevisioncounterFields := schema.RbacPolicyRevisionCounter{}.Fields()
	_ = rbacpolicyrevisioncounterFields
	// rbacpolicyrevisioncounterDescLastRevision is the schema descriptor for last_revision field.
	rbacpolicyrevisioncounterDescLastRevision := rbacpolicyrevisioncounterFields[1].Descriptor()
	// rbacpolicyrevisioncounter.DefaultLastRevision holds the default value on creation for the last_revision field.
	rbacpolicyrevisioncounter.DefaultLastRevision = rbacpolicyrevisioncounterDescLastRevision.Default.(int64)
	// rbacpolicyrevisioncounter.LastRevisionValidator is a validator for the "last_revision" field. It is called by the builders before save.
	rbacpolicyrevisioncounter.LastRevisionValidator = rbacpolicyrevisioncounterDescLastRevision.Validators[0].(func(int64) error)
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[2].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDescription is the schema descriptor for description field.
	roleDescDescription := roleFields[3].Descriptor()
	// role.DefaultDescription holds the default value on creation for the description field.
	role.DefaultDescription = roleDescDescription.Default.(string)
	// role.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	role.DescriptionValidator = roleDescDescription.Validators[0].(func(string) error)
	// roleDescActive is the schema descriptor for active field.
	roleDescActive := roleFields[4].Descriptor()
	// role.DefaultActive holds the default value on creation for the active field.
	role.DefaultActive = roleDescActive.Default.(bool)
	// roleDescIsSystem is the schema descriptor for is_system field.
	roleDescIsSystem := roleFields[5].Descriptor()
	// role.DefaultIsSystem holds the default value on creation for the is_system field.
	role.DefaultIsSystem = roleDescIsSystem.Default.(bool)
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleFields[6].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() int64)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleFields[7].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() int64)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() int64)
	rolepermissionFields := schema.RolePermission{}.Fields()
	_ = rolepermissionFields
	// rolepermissionDescCreatedAt is the schema descriptor for created_at field.
	rolepermissionDescCreatedAt := rolepermissionFields[3].Descriptor()
	// rolepermission.DefaultCreatedAt holds the default value on creation for the created_at field.
	rolepermission.DefaultCreatedAt = rolepermissionDescCreatedAt.Default.(func() int64)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[2].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = func() func(string) error {
		validators := userDescNickname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(nickname string) error {
			for _, fn := range fns {
				if err := fn(nickname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[3].Descriptor()
	// user.UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	user.UsernameValidator = func() func(string) error {
		validators := userDescUsername.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(username string) error {
			for _, fn := range fns {
				if err := fn(username); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[4].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescTokenVersion is the schema descriptor for token_version field.
	userDescTokenVersion := userFields[5].Descriptor()
	// user.DefaultTokenVersion holds the default value on creation for the token_version field.
	user.DefaultTokenVersion = userDescTokenVersion.Default.(int64)
	// userDescStatus is the schema descriptor for status field.
	userDescStatus := userFields[6].Descriptor()
	// user.DefaultStatus holds the default value on creation for the status field.
	user.DefaultStatus = userDescStatus.Default.(int64)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[8].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() int64)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[9].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() int64)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() int64)
	userroleFields := schema.UserRole{}.Fields()
	_ = userroleFields
	// userroleDescCreatedAt is the schema descriptor for created_at field.
	userroleDescCreatedAt := userroleFields[3].Descriptor()
	// userrole.DefaultCreatedAt holds the default value on creation for the created_at field.
	userrole.DefaultCreatedAt = userroleDescCreatedAt.Default.(func() int64)
}
