apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aegiscore-user-service.configMapName" . }}
  labels:
    {{- include "aegiscore-user-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
