// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/role/application (interfaces: RoleStore,UserRoleStore,RolePermissionStore,PermissionLookup)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=command github.com/aegiscore/user-service/internal/features/role/application RoleStore,UserRoleStore,RolePermissionStore,PermissionLookup
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	application "github.com/aegiscore/user-service/internal/features/role/application"
	domain "github.com/aegiscore/user-service/internal/features/role/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleStore is a mock of RoleStore interface.
type MockRoleStore struct {
	ctrl     *gomock.Controller
	recorder *MockRoleStoreMockRecorder
	isgomock struct{}
}

// MockRoleStoreMockRecorder is the mock recorder for MockRoleStore.
type MockRoleStoreMockRecorder struct {
	mock *MockRoleStore
}

// NewMockRoleStore creates a new mock instance.
func NewMockRoleStore(ctrl *gomock.Controller) *MockRoleStore {
	mock := &MockRoleStore{ctrl: ctrl}
	mock.recorder = &MockRoleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleStore) EXPECT() *MockRoleStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRoleStore) Create(ctx context.Context, input application.CreateRoleInput, change application.PolicyChange) (*application.RoleWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input, change)
	ret0, _ := ret[0].(*application.RoleWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRoleStoreMockRecorder) Create(ctx, input, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleStore)(nil).Create), ctx, input, change)
}

// GetByRoleID mocks base method.
func (m *MockRoleStore) GetByRoleID(ctx context.Context, roleID uuid.UUID) (*domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoleID", ctx, roleID)
	ret0, _ := ret[0].(*domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleID indicates an expected call of GetByRoleID.
func (mr *MockRoleStoreMockRecorder) GetByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleID", reflect.TypeOf((*MockRoleStore)(nil).GetByRoleID), ctx, roleID)
}

// GetByRoleIDs mocks base method.
func (m *MockRoleStore) GetByRoleIDs(ctx context.Context, roleIDs []uuid.UUID) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByRoleIDs", ctx, roleIDs)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByRoleIDs indicates an expected call of GetByRoleIDs.
func (mr *MockRoleStoreMockRecorder) GetByRoleIDs(ctx, roleIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByRoleIDs", reflect.TypeOf((*MockRoleStore)(nil).GetByRoleIDs), ctx, roleIDs)
}

// List mocks base method.
func (m *MockRoleStore) List(ctx context.Context, input application.ListRolesInput) ([]domain.Role, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockRoleStoreMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleStore)(nil).List), ctx, input)
}

// SetActive mocks base method.
func (m *MockRoleStore) SetActive(ctx context.Context, roleID uuid.UUID, active bool, change application.PolicyChange) (application.PolicyWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, roleID, active, change)
	ret0, _ := ret[0].(application.PolicyWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActive indicates an expected call of SetActive.
func (mr *MockRoleStoreMockRecorder) SetActive(ctx, roleID, active, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockRoleStore)(nil).SetActive), ctx, roleID, active, change)
}

// Update mocks base method.
func (m *MockRoleStore) Update(ctx context.Context, input application.UpdateRoleInput, change application.PolicyChange) (application.PolicyWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input, change)
	ret0, _ := ret[0].(application.PolicyWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockRoleStoreMockRecorder) Update(ctx, input, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleStore)(nil).Update), ctx, input, change)
}

// MockUserRoleStore is a mock of UserRoleStore interface.
type MockUserRoleStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserRoleStoreMockRecorder
	isgomock struct{}
}

// MockUserRoleStoreMockRecorder is the mock recorder for MockUserRoleStore.
type MockUserRoleStoreMockRecorder struct {
	mock *MockUserRoleStore
}

// NewMockUserRoleStore creates a new mock instance.
func NewMockUserRoleStore(ctrl *gomock.Controller) *MockUserRoleStore {
	mock := &MockUserRoleStore{ctrl: ctrl}
	mock.recorder = &MockUserRoleStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRoleStore) EXPECT() *MockUserRoleStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockUserRoleStore) Add(ctx context.Context, userID, roleID uuid.UUID, change application.PolicyChange) (application.RolesWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, userID, roleID, change)
	ret0, _ := ret[0].(application.RolesWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockUserRoleStoreMockRecorder) Add(ctx, userID, roleID, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockUserRoleStore)(nil).Add), ctx, userID, roleID, change)
}

// ListByUserID mocks base method.
func (m *MockUserRoleStore) ListByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockUserRoleStoreMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockUserRoleStore)(nil).ListByUserID), ctx, userID)
}

// Remove mocks base method.
func (m *MockUserRoleStore) Remove(ctx context.Context, userID, roleID uuid.UUID, change application.PolicyChange) (application.RolesWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, userID, roleID, change)
	ret0, _ := ret[0].(application.RolesWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove indicates an expected call of Remove.
func (mr *MockUserRoleStoreMockRecorder) Remove(ctx, userID, roleID, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockUserRoleStore)(nil).Remove), ctx, userID, roleID, change)
}

// Replace mocks base method.
func (m *MockUserRoleStore) Replace(ctx context.Context, userID uuid.UUID, roleIDs []uuid.UUID, change application.PolicyChange) (application.RolesWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, userID, roleIDs, change)
	ret0, _ := ret[0].(application.RolesWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockUserRoleStoreMockRecorder) Replace(ctx, userID, roleIDs, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockUserRoleStore)(nil).Replace), ctx, userID, roleIDs, change)
}

// MockRolePermissionStore is a mock of RolePermissionStore interface.
type MockRolePermissionStore struct {
	ctrl     *gomock.Controller
	recorder *MockRolePermissionStoreMockRecorder
	isgomock struct{}
}

// MockRolePermissionStoreMockRecorder is the mock recorder for MockRolePermissionStore.
type MockRolePermissionStoreMockRecorder struct {
	mock *MockRolePermissionStore
}

// NewMockRolePermissionStore creates a new mock instance.
func NewMockRolePermissionStore(ctrl *gomock.Controller) *MockRolePermissionStore {
	mock := &MockRolePermissionStore{ctrl: ctrl}
	mock.recorder = &MockRolePermissionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolePermissionStore) EXPECT() *MockRolePermissionStoreMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRolePermissionStore) Add(ctx context.Context, roleID uuid.UUID, permission application.PermissionReference, change application.PolicyChange) (application.PermissionsWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, roleID, permission, change)
	ret0, _ := ret[0].(application.PermissionsWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Add indicates an expected call of Add.
func (mr *MockRolePermissionStoreMockRecorder) Add(ctx, roleID, permission, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRolePermissionStore)(nil).Add), ctx, roleID, permission, change)
}

// ListByRoleID mocks base method.
func (m *MockRolePermissionStore) ListByRoleID(ctx context.Context, roleID uuid.UUID) ([]application.PermissionReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByRoleID", ctx, roleID)
	ret0, _ := ret[0].([]application.PermissionReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByRoleID indicates an expected call of ListByRoleID.
func (mr *MockRolePermissionStoreMockRecorder) ListByRoleID(ctx, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByRoleID", reflect.TypeOf((*MockRolePermissionStore)(nil).ListByRoleID), ctx, roleID)
}

// Remove mocks base method.
func (m *MockRolePermissionStore) Remove(ctx context.Context, roleID, permissionID uuid.UUID, change application.PolicyChange) (application.PermissionsWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, roleID, permissionID, change)
	ret0, _ := ret[0].(application.PermissionsWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Remove indicates an expected call of Remove.
func (mr *MockRolePermissionStoreMockRecorder) Remove(ctx, roleID, permissionID, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRolePermissionStore)(nil).Remove), ctx, roleID, permissionID, change)
}

// Replace mocks base method.
func (m *MockRolePermissionStore) Replace(ctx context.Context, roleID uuid.UUID, permissions []application.PermissionReference, change application.PolicyChange) (application.PermissionsWriteResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replace", ctx, roleID, permissions, change)
	ret0, _ := ret[0].(application.PermissionsWriteResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replace indicates an expected call of Replace.
func (mr *MockRolePermissionStoreMockRecorder) Replace(ctx, roleID, permissions, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replace", reflect.TypeOf((*MockRolePermissionStore)(nil).Replace), ctx, roleID, permissions, change)
}

// MockPermissionLookup is a mock of PermissionLookup interface.
type MockPermissionLookup struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionLookupMockRecorder
	isgomock struct{}
}

// MockPermissionLookupMockRecorder is the mock recorder for MockPermissionLookup.
type MockPermissionLookupMockRecorder struct {
	mock *MockPermissionLookup
}

// NewMockPermissionLookup creates a new mock instance.
func NewMockPermissionLookup(ctrl *gomock.Controller) *MockPermissionLookup {
	mock := &MockPermissionLookup{ctrl: ctrl}
	mock.recorder = &MockPermissionLookupMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionLookup) EXPECT() *MockPermissionLookupMockRecorder {
	return m.recorder
}

// GetByPermissionID mocks base method.
func (m *MockPermissionLookup) GetByPermissionID(ctx context.Context, permissionID uuid.UUID) (*application.PermissionReference, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPermissionID", ctx, permissionID)
	ret0, _ := ret[0].(*application.PermissionReference)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPermissionID indicates an expected call of GetByPermissionID.
func (mr *MockPermissionLookupMockRecorder) GetByPermissionID(ctx, permissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPermissionID", reflect.TypeOf((*MockPermissionLookup)(nil).GetByPermissionID), ctx, permissionID)
}
