// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// PermissionsColumns holds the columns for the "permissions" table.
	PermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "权限ID"},
		{Name: "permission_id", Type: field.TypeUUID, Unique: true, Comment: "外部权限ID"},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "权限名称"},
		{Name: "description", Type: field.TypeString, Size: 512, Comment: "权限说明", Default: ""},
		{Name: "module", Type: field.TypeString, Size: 64, Comment: "权限所属模块"},
		{Name: "http_method", Type: field.TypeString, Size: 16, Comment: "HTTP 方法"},
		{Name: "path_template", Type: field.TypeString, Size: 512, Comment: "路径模板"},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
		{Name: "updated_at", Type: field.TypeInt64, Comment: "更新时间戳毫秒"},
	}
	// PermissionsTable holds the schema information for the "permissions" table.
	PermissionsTable = &schema.Table{
		Name:       "permissions",
		Columns:    PermissionsColumns,
		PrimaryKey: []*schema.Column{PermissionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "permission_http_method_path_template",
				Unique:  true,
				Columns: []*schema.Column{PermissionsColumns[5], PermissionsColumns[6]},
			},
			{
				Name:    "permission_module_permission_id",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[4], PermissionsColumns[1]},
			},
			{
				Name:    "permission_http_method_permission_id",
				Unique:  false,
				Columns: []*schema.Column{PermissionsColumns[5], PermissionsColumns[1]},
			},
		},
	}
	// RbacPolicyOutboxEventsColumns holds the columns for the "rbac_policy_outbox_events" table.
	RbacPolicyOutboxEventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "RBAC policy outbox 内部ID"},
		{Name: "event_id", Type: field.TypeUUID, Unique: true, Comment: "稳定 outbox event ID"},
		{Name: "kind", Type: field.TypeString, Size: 32, Comment: "事件类型"},
		{Name: "reason", Type: field.TypeString, Size: 64, Comment: "触发 policy 变更的稳定原因"},
		{Name: "role_id", Type: field.TypeUUID, Nullable: true, Comment: "相关外部角色ID"},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true, Comment: "相关外部用户ID"},
		{Name: "permission_id", Type: field.TypeUUID, Nullable: true, Comment: "相关外部权限ID"},
		{Name: "status", Type: field.TypeString, Size: 16, Comment: "投递状态", Default: "pending"},
		{Name: "attempt_count", Type: field.TypeInt, Comment: "投递尝试次数", Default: 0},
		{Name: "next_attempt_at", Type: field.TypeInt64, Comment: "下次允许尝试的时间戳毫秒"},
		{Name: "last_error", Type: field.TypeString, Nullable: true, Size: 2048, Comment: "最近一次投递错误"},
		{Name: "claim_token", Type: field.TypeUUID, Nullable: true, Comment: "当前 dispatcher claim token"},
		{Name: "claimed_until", Type: field.TypeInt64, Nullable: true, Comment: "当前 claim lease 截止时间戳毫秒"},
		{Name: "idempotency_key", Type: field.TypeString, Unique: true, Size: 128, Comment: "稳定投递幂等键"},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
		{Name: "updated_at", Type: field.TypeInt64, Comment: "更新时间戳毫秒"},
		{Name: "delivered_at", Type: field.TypeInt64, Nullable: true, Comment: "投递完成时间戳毫秒"},
		{Name: "revision", Type: field.TypeInt64, Unique: true, Comment: "关联的 RBAC policy revision"},
	}
	// RbacPolicyOutboxEventsTable holds the schema information for the "rbac_policy_outbox_events" table.
	RbacPolicyOutboxEventsTable = &schema.Table{
		Name:       "rbac_policy_outbox_events",
		Columns:    RbacPolicyOutboxEventsColumns,
		PrimaryKey: []*schema.Column{RbacPolicyOutboxEventsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "rbac_policy_outbox_events_rbac_policy_revisions_outbox_event",
				Columns:    []*schema.Column{RbacPolicyOutboxEventsColumns[17]},
				RefColumns: []*schema.Column{RbacPolicyRevisionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rbacpolicyoutboxevent_status_next_attempt_at_revision",
				Unique:  false,
				Columns: []*schema.Column{RbacPolicyOutboxEventsColumns[7], RbacPolicyOutboxEventsColumns[9], RbacPolicyOutboxEventsColumns[17]},
			},
			{
				Name:    "rbacpolicyoutboxevent_status_claimed_until_revision",
				Unique:  false,
				Columns: []*schema.Column{RbacPolicyOutboxEventsColumns[7], RbacPolicyOutboxEventsColumns[12], RbacPolicyOutboxEventsColumns[17]},
			},
		},
	}
	// RbacPolicyRevisionsColumns holds the columns for the "rbac_policy_revisions" table.
	RbacPolicyRevisionsColumns = []*schema.Column{
		{Name: "revision", Type: field.TypeInt64, Increment: true, Comment: "单调递增的 RBAC policy revision"},
		{Name: "reason", Type: field.TypeString, Size: 64, Comment: "触发 policy 变更的稳定原因"},
		{Name: "role_id", Type: field.TypeUUID, Nullable: true, Comment: "相关外部角色ID"},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true, Comment: "相关外部用户ID"},
		{Name: "permission_id", Type: field.TypeUUID, Nullable: true, Comment: "相关外部权限ID"},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
	}
	// RbacPolicyRevisionsTable holds the schema information for the "rbac_policy_revisions" table.
	RbacPolicyRevisionsTable = &schema.Table{
		Name:       "rbac_policy_revisions",
		Columns:    RbacPolicyRevisionsColumns,
		PrimaryKey: []*schema.Column{RbacPolicyRevisionsColumns[0]},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "角色ID"},
		{Name: "role_id", Type: field.TypeUUID, Unique: true, Comment: "外部角色ID"},
		{Name: "name", Type: field.TypeString, Size: 128, Comment: "角色名称"},
		{Name: "description", Type: field.TypeString, Size: 512, Comment: "角色说明", Default: ""},
		{Name: "active", Type: field.TypeBool, Comment: "角色是否启用", Default: true},
		{Name: "is_system", Type: field.TypeBool, Comment: "是否系统角色", Default: false},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
		{Name: "updated_at", Type: field.TypeInt64, Comment: "更新时间戳毫秒"},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_active_role_id",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[4], RolesColumns[1]},
			},
			{
				Name:    "role_is_system_role_id",
				Unique:  false,
				Columns: []*schema.Column{RolesColumns[5], RolesColumns[1]},
			},
		},
	}
	// RolePermissionsColumns holds the columns for the "role_permissions" table.
	RolePermissionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "角色权限绑定ID"},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
		{Name: "permission_id", Type: field.TypeInt64, Comment: "权限内部ID"},
		{Name: "role_id", Type: field.TypeInt64, Comment: "角色内部ID"},
	}
	// RolePermissionsTable holds the schema information for the "role_permissions" table.
	RolePermissionsTable = &schema.Table{
		Name:       "role_permissions",
		Columns:    RolePermissionsColumns,
		PrimaryKey: []*schema.Column{RolePermissionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "role_permissions_permissions_role_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[2]},
				RefColumns: []*schema.Column{PermissionsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "role_permissions_roles_role_permissions",
				Columns:    []*schema.Column{RolePermissionsColumns[3]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "rolepermission_role_id_permission_id",
				Unique:  true,
				Columns: []*schema.Column{RolePermissionsColumns[3], RolePermissionsColumns[2]},
			},
			{
				Name:    "rolepermission_permission_id_role_id",
				Unique:  false,
				Columns: []*schema.Column{RolePermissionsColumns[2], RolePermissionsColumns[3]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "用户ID"},
		{Name: "user_id", Type: field.TypeUUID, Unique: true, Comment: "外部用户ID"},
		{Name: "nickname", Type: field.TypeString, Size: 128, Comment: "用户昵称"},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 255, Comment: "用户名"},
		{Name: "password_hash", Type: field.TypeString, Comment: "密码哈希"},
		{Name: "token_version", Type: field.TypeInt64, Comment: "认证令牌版本", Default: 1},
		{Name: "status", Type: field.TypeInt64, Comment: "用户状态：100 正常，200 冻结/停用，300 必须修改密码", Default: 100},
		{Name: "deleted_at", Type: field.TypeInt64, Nullable: true, Comment: "软删除时间戳毫秒，NULL 表示未删除"},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
		{Name: "updated_at", Type: field.TypeInt64, Comment: "更新时间戳毫秒"},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "users_nickname_trgm",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[2]},
				Annotation: &entsql.IndexAnnotation{
					OpClass: "gin_trgm_ops",
					Types: map[string]string{
						"postgres": "GIN",
					},
				},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6]},
			},
			{
				Name:    "user_deleted_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[7]},
			},
			{
				Name:    "user_deleted_at_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[7], UsersColumns[1]},
			},
			{
				Name:    "user_status_deleted_at_user_id",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[6], UsersColumns[7], UsersColumns[1]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true, Comment: "用户角色绑定ID"},
		{Name: "created_at", Type: field.TypeInt64, Comment: "创建时间戳毫秒"},
		{Name: "role_id", Type: field.TypeInt64, Comment: "角色内部ID"},
		{Name: "user_id", Type: field.TypeInt64, Comment: "用户内部ID"},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_roles_roles_user_roles",
				Columns:    []*schema.Column{UserRolesColumns[2]},
				RefColumns: []*schema.Column{RolesColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "user_roles_users_user_roles",
				Columns:    []*schema.Column{UserRolesColumns[3]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "userrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[3], UserRolesColumns[2]},
			},
			{
				Name:    "userrole_role_id_user_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[2], UserRolesColumns[3]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		PermissionsTable,
		RbacPolicyOutboxEventsTable,
		RbacPolicyRevisionsTable,
		RolesTable,
		RolePermissionsTable,
		UsersTable,
		UserRolesTable,
	}
)

func init() {
	RbacPolicyOutboxEventsTable.ForeignKeys[0].RefTable = RbacPolicyRevisionsTable
	RolePermissionsTable.ForeignKeys[0].RefTable = PermissionsTable
	RolePermissionsTable.ForeignKeys[1].RefTable = RolesTable
	UserRolesTable.ForeignKeys[0].RefTable = RolesTable
	UserRolesTable.ForeignKeys[1].RefTable = UsersTable
}
