// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/cmd (interfaces: rbacSeedService)
//
// Generated by this command:
//
//	mockgen -destination=mock_rbac_test.go -package=main github.com/aegiscore/user-service/cmd rbacSeedService
//

// Package main is a generated GoMock package.
package main

import (
	context "context"
	reflect "reflect"

	seed "github.com/aegiscore/user-service/internal/features/role/application/seed"
	gomock "go.uber.org/mock/gomock"
)

// MockrbacSeedService is a mock of rbacSeedService interface.
type MockrbacSeedService struct {
	ctrl     *gomock.Controller
	recorder *MockrbacSeedServiceMockRecorder
	isgomock struct{}
}

// MockrbacSeedServiceMockRecorder is the mock recorder for MockrbacSeedService.
type MockrbacSeedServiceMockRecorder struct {
	mock *MockrbacSeedService
}

// NewMockrbacSeedService creates a new mock instance.
func NewMockrbacSeedService(ctrl *gomock.Controller) *MockrbacSeedService {
	mock := &MockrbacSeedService{ctrl: ctrl}
	mock.recorder = &MockrbacSeedServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockrbacSeedService) EXPECT() *MockrbacSeedServiceMockRecorder {
	return m.recorder
}

// Seed mocks base method.
func (m *MockrbacSeedService) Seed(ctx context.Context, opts seed.SeedOptions) (seed.SeedResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Seed", ctx, opts)
	ret0, _ := ret[0].(seed.SeedResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Seed indicates an expected call of Seed.
func (mr *MockrbacSeedServiceMockRecorder) Seed(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seed", reflect.TypeOf((*MockrbacSeedService)(nil).Seed), ctx, opts)
}
