// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/auth/application (interfaces: UserTokenVersionStore,TokenVersionCache)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=validators github.com/aegiscore/user-service/internal/features/auth/application UserTokenVersionStore,TokenVersionCache
//

// Package validators is a generated GoMock package.
package validators

import (
	context "context"
	reflect "reflect"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserTokenVersionStore is a mock of UserTokenVersionStore interface.
type MockUserTokenVersionStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserTokenVersionStoreMockRecorder
	isgomock struct{}
}

// MockUserTokenVersionStoreMockRecorder is the mock recorder for MockUserTokenVersionStore.
type MockUserTokenVersionStoreMockRecorder struct {
	mock *MockUserTokenVersionStore
}

// NewMockUserTokenVersionStore creates a new mock instance.
func NewMockUserTokenVersionStore(ctrl *gomock.Controller) *MockUserTokenVersionStore {
	mock := &MockUserTokenVersionStore{ctrl: ctrl}
	mock.recorder = &MockUserTokenVersionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTokenVersionStore) EXPECT() *MockUserTokenVersionStoreMockRecorder {
	return m.recorder
}

// GetTokenVersion mocks base method.
func (m *MockUserTokenVersionStore) GetTokenVersion(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenVersion indicates an expected call of GetTokenVersion.
func (mr *MockUserTokenVersionStoreMockRecorder) GetTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenVersion", reflect.TypeOf((*MockUserTokenVersionStore)(nil).GetTokenVersion), ctx, userID)
}

// IncrementTokenVersion mocks base method.
func (m *MockUserTokenVersionStore) IncrementTokenVersion(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementTokenVersion indicates an expected call of IncrementTokenVersion.
func (mr *MockUserTokenVersionStoreMockRecorder) IncrementTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTokenVersion", reflect.TypeOf((*MockUserTokenVersionStore)(nil).IncrementTokenVersion), ctx, userID)
}

// MockTokenVersionCache is a mock of TokenVersionCache interface.
type MockTokenVersionCache struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVersionCacheMockRecorder
	isgomock struct{}
}

// MockTokenVersionCacheMockRecorder is the mock recorder for MockTokenVersionCache.
type MockTokenVersionCacheMockRecorder struct {
	mock *MockTokenVersionCache
}

// NewMockTokenVersionCache creates a new mock instance.
func NewMockTokenVersionCache(ctrl *gomock.Controller) *MockTokenVersionCache {
	mock := &MockTokenVersionCache{ctrl: ctrl}
	mock.recorder = &MockTokenVersionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVersionCache) EXPECT() *MockTokenVersionCacheMockRecorder {
	return m.recorder
}

// CacheTokenVersion mocks base method.
func (m *MockTokenVersionCache) CacheTokenVersion(ctx context.Context, userID string, tokenVersion int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheTokenVersion", ctx, userID, tokenVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheTokenVersion indicates an expected call of CacheTokenVersion.
func (mr *MockTokenVersionCacheMockRecorder) CacheTokenVersion(ctx, userID, tokenVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheTokenVersion", reflect.TypeOf((*MockTokenVersionCache)(nil).CacheTokenVersion), ctx, userID, tokenVersion)
}

// DeleteCachedTokenVersion mocks base method.
func (m *MockTokenVersionCache) DeleteCachedTokenVersion(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCachedTokenVersion", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCachedTokenVersion indicates an expected call of DeleteCachedTokenVersion.
func (mr *MockTokenVersionCacheMockRecorder) DeleteCachedTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCachedTokenVersion", reflect.TypeOf((*MockTokenVersionCache)(nil).DeleteCachedTokenVersion), ctx, userID)
}

// GetCachedTokenVersion mocks base method.
func (m *MockTokenVersionCache) GetCachedTokenVersion(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedTokenVersion indicates an expected call of GetCachedTokenVersion.
func (mr *MockTokenVersionCacheMockRecorder) GetCachedTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedTokenVersion", reflect.TypeOf((*MockTokenVersionCache)(nil).GetCachedTokenVersion), ctx, userID)
}
