// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/auth/application/credentials (interfaces: Verifier)
//
// Generated by this command:
//
//	mockgen -destination=mock_credentials_test.go -package=command github.com/aegiscore/user-service/internal/features/auth/application/credentials Verifier
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	domain "github.com/aegiscore/user-service/internal/features/auth/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVerifier is a mock of Verifier interface.
type MockVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockVerifierMockRecorder
	isgomock struct{}
}

// MockVerifierMockRecorder is the mock recorder for MockVerifier.
type MockVerifierMockRecorder struct {
	mock *MockVerifier
}

// NewMockVerifier creates a new mock instance.
func NewMockVerifier(ctrl *gomock.Controller) *MockVerifier {
	mock := &MockVerifier{ctrl: ctrl}
	mock.recorder = &MockVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVerifier) EXPECT() *MockVerifierMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockVerifier) ChangePassword(ctx context.Context, userID uuid.UUID, newPassword string) (*domain.CredentialUpdateResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, userID, newPassword)
	ret0, _ := ret[0].(*domain.CredentialUpdateResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockVerifierMockRecorder) ChangePassword(ctx, userID, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockVerifier)(nil).ChangePassword), ctx, userID, newPassword)
}

// VerifyPassword mocks base method.
func (m *MockVerifier) VerifyPassword(ctx context.Context, username, plainPassword string) (*domain.UserCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyPassword", ctx, username, plainPassword)
	ret0, _ := ret[0].(*domain.UserCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyPassword indicates an expected call of VerifyPassword.
func (mr *MockVerifierMockRecorder) VerifyPassword(ctx, username, plainPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyPassword", reflect.TypeOf((*MockVerifier)(nil).VerifyPassword), ctx, username, plainPassword)
}
