// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/auth/application/tokens (interfaces: Issuer)
//
// Generated by this command:
//
//	mockgen -destination=mock_tokens_test.go -package=command github.com/aegiscore/user-service/internal/features/auth/application/tokens Issuer
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	tokens "github.com/aegiscore/user-service/internal/features/auth/application/tokens"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockIssuer is a mock of Issuer interface.
type MockIssuer struct {
	ctrl     *gomock.Controller
	recorder *MockIssuerMockRecorder
	isgomock struct{}
}

// MockIssuerMockRecorder is the mock recorder for MockIssuer.
type MockIssuerMockRecorder struct {
	mock *MockIssuer
}

// NewMockIssuer creates a new mock instance.
func NewMockIssuer(ctrl *gomock.Controller) *MockIssuer {
	mock := &MockIssuer{ctrl: ctrl}
	mock.recorder = &MockIssuerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssuer) EXPECT() *MockIssuerMockRecorder {
	return m.recorder
}

// IssuePasswordChangeToken mocks base method.
func (m *MockIssuer) IssuePasswordChangeToken(ctx context.Context, userID uuid.UUID, tokenVersion int64, sessionID string) (*tokens.TokenResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssuePasswordChangeToken", ctx, userID, tokenVersion, sessionID)
	ret0, _ := ret[0].(*tokens.TokenResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssuePasswordChangeToken indicates an expected call of IssuePasswordChangeToken.
func (mr *MockIssuerMockRecorder) IssuePasswordChangeToken(ctx, userID, tokenVersion, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssuePasswordChangeToken", reflect.TypeOf((*MockIssuer)(nil).IssuePasswordChangeToken), ctx, userID, tokenVersion, sessionID)
}

// IssueTokenPair mocks base method.
func (m *MockIssuer) IssueTokenPair(ctx context.Context, userID uuid.UUID, tokenVersion int64, sessionID string) (*tokens.IssuedTokenPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IssueTokenPair", ctx, userID, tokenVersion, sessionID)
	ret0, _ := ret[0].(*tokens.IssuedTokenPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IssueTokenPair indicates an expected call of IssueTokenPair.
func (mr *MockIssuerMockRecorder) IssueTokenPair(ctx, userID, tokenVersion, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IssueTokenPair", reflect.TypeOf((*MockIssuer)(nil).IssueTokenPair), ctx, userID, tokenVersion, sessionID)
}

// ParsePasswordChangeToken mocks base method.
func (m *MockIssuer) ParsePasswordChangeToken(ctx context.Context, token string) (*tokens.Claims, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParsePasswordChangeToken", ctx, token)
	ret0, _ := ret[0].(*tokens.Claims)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParsePasswordChangeToken indicates an expected call of ParsePasswordChangeToken.
func (mr *MockIssuerMockRecorder) ParsePasswordChangeToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParsePasswordChangeToken", reflect.TypeOf((*MockIssuer)(nil).ParsePasswordChangeToken), ctx, token)
}

// ParseRefreshToken mocks base method.
func (m *MockIssuer) ParseRefreshToken(ctx context.Context, token string) (*tokens.Claims, uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseRefreshToken", ctx, token)
	ret0, _ := ret[0].(*tokens.Claims)
	ret1, _ := ret[1].(uuid.UUID)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ParseRefreshToken indicates an expected call of ParseRefreshToken.
func (mr *MockIssuerMockRecorder) ParseRefreshToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseRefreshToken", reflect.TypeOf((*MockIssuer)(nil).ParseRefreshToken), ctx, token)
}
