// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/role/application/command (interfaces: RoleCommandService)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=rolehttp github.com/aegiscore/user-service/internal/features/role/application/command RoleCommandService
//

// Package rolehttp is a generated GoMock package.
package rolehttp

import (
	context "context"
	reflect "reflect"

	command "github.com/aegiscore/user-service/internal/features/role/application/command"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleCommandService is a mock of RoleCommandService interface.
type MockRoleCommandService struct {
	ctrl     *gomock.Controller
	recorder *MockRoleCommandServiceMockRecorder
	isgomock struct{}
}

// MockRoleCommandServiceMockRecorder is the mock recorder for MockRoleCommandService.
type MockRoleCommandServiceMockRecorder struct {
	mock *MockRoleCommandService
}

// NewMockRoleCommandService creates a new mock instance.
func NewMockRoleCommandService(ctrl *gomock.Controller) *MockRoleCommandService {
	mock := &MockRoleCommandService{ctrl: ctrl}
	mock.recorder = &MockRoleCommandServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleCommandService) EXPECT() *MockRoleCommandServiceMockRecorder {
	return m.recorder
}

// AddRolePermission mocks base method.
func (m *MockRoleCommandService) AddRolePermission(ctx context.Context, cmd command.RolePermissionCommand) (*command.PermissionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRolePermission", ctx, cmd)
	ret0, _ := ret[0].(*command.PermissionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRolePermission indicates an expected call of AddRolePermission.
func (mr *MockRoleCommandServiceMockRecorder) AddRolePermission(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRolePermission", reflect.TypeOf((*MockRoleCommandService)(nil).AddRolePermission), ctx, cmd)
}

// AddUserRole mocks base method.
func (m *MockRoleCommandService) AddUserRole(ctx context.Context, cmd command.UserRoleCommand) (*command.RolesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserRole", ctx, cmd)
	ret0, _ := ret[0].(*command.RolesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddUserRole indicates an expected call of AddUserRole.
func (mr *MockRoleCommandServiceMockRecorder) AddUserRole(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserRole", reflect.TypeOf((*MockRoleCommandService)(nil).AddUserRole), ctx, cmd)
}

// CreateRole mocks base method.
func (m *MockRoleCommandService) CreateRole(ctx context.Context, cmd command.CreateRoleCommand) (*command.RoleResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, cmd)
	ret0, _ := ret[0].(*command.RoleResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRoleCommandServiceMockRecorder) CreateRole(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRoleCommandService)(nil).CreateRole), ctx, cmd)
}

// RemoveRolePermission mocks base method.
func (m *MockRoleCommandService) RemoveRolePermission(ctx context.Context, cmd command.RolePermissionCommand) (*command.PermissionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRolePermission", ctx, cmd)
	ret0, _ := ret[0].(*command.PermissionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveRolePermission indicates an expected call of RemoveRolePermission.
func (mr *MockRoleCommandServiceMockRecorder) RemoveRolePermission(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRolePermission", reflect.TypeOf((*MockRoleCommandService)(nil).RemoveRolePermission), ctx, cmd)
}

// RemoveUserRole mocks base method.
func (m *MockRoleCommandService) RemoveUserRole(ctx context.Context, cmd command.UserRoleCommand) (*command.RolesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveUserRole", ctx, cmd)
	ret0, _ := ret[0].(*command.RolesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveUserRole indicates an expected call of RemoveUserRole.
func (mr *MockRoleCommandServiceMockRecorder) RemoveUserRole(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveUserRole", reflect.TypeOf((*MockRoleCommandService)(nil).RemoveUserRole), ctx, cmd)
}

// ReplaceRolePermissions mocks base method.
func (m *MockRoleCommandService) ReplaceRolePermissions(ctx context.Context, cmd command.ReplaceRolePermissionsCommand) (*command.PermissionsResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceRolePermissions", ctx, cmd)
	ret0, _ := ret[0].(*command.PermissionsResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceRolePermissions indicates an expected call of ReplaceRolePermissions.
func (mr *MockRoleCommandServiceMockRecorder) ReplaceRolePermissions(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceRolePermissions", reflect.TypeOf((*MockRoleCommandService)(nil).ReplaceRolePermissions), ctx, cmd)
}

// ReplaceUserRoles mocks base method.
func (m *MockRoleCommandService) ReplaceUserRoles(ctx context.Context, cmd command.ReplaceUserRolesCommand) (*command.RolesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReplaceUserRoles", ctx, cmd)
	ret0, _ := ret[0].(*command.RolesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReplaceUserRoles indicates an expected call of ReplaceUserRoles.
func (mr *MockRoleCommandServiceMockRecorder) ReplaceUserRoles(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReplaceUserRoles", reflect.TypeOf((*MockRoleCommandService)(nil).ReplaceUserRoles), ctx, cmd)
}

// SetRoleActive mocks base method.
func (m *MockRoleCommandService) SetRoleActive(ctx context.Context, cmd command.SetRoleActiveCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetRoleActive", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetRoleActive indicates an expected call of SetRoleActive.
func (mr *MockRoleCommandServiceMockRecorder) SetRoleActive(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoleActive", reflect.TypeOf((*MockRoleCommandService)(nil).SetRoleActive), ctx, cmd)
}

// UpdateRole mocks base method.
func (m *MockRoleCommandService) UpdateRole(ctx context.Context, cmd command.UpdateRoleCommand) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, cmd)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockRoleCommandServiceMockRecorder) UpdateRole(ctx, cmd any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockRoleCommandService)(nil).UpdateRole), ctx, cmd)
}
