// Code generated by ent, DO NOT EDIT.

package rbacpolicyoutboxevent

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/aegiscore/user-service/internal/persistence/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldID, id))
}

// EventID applies equality check predicate on the "event_id" field. It's identical to EventIDEQ.
func EventID(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldEventID, v))
}

// Revision applies equality check predicate on the "revision" field. It's identical to RevisionEQ.
func Revision(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldRevision, v))
}

// Kind applies equality check predicate on the "kind" field. It's identical to KindEQ.
func Kind(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldKind, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldReason, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldRoleID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldUserID, v))
}

// PermissionID applies equality check predicate on the "permission_id" field. It's identical to PermissionIDEQ.
func PermissionID(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldPermissionID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldStatus, v))
}

// AttemptCount applies equality check predicate on the "attempt_count" field. It's identical to AttemptCountEQ.
func AttemptCount(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldAttemptCount, v))
}

// NextAttemptAt applies equality check predicate on the "next_attempt_at" field. It's identical to NextAttemptAtEQ.
func NextAttemptAt(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldNextAttemptAt, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldLastError, v))
}

// IdempotencyKey applies equality check predicate on the "idempotency_key" field. It's identical to IdempotencyKeyEQ.
func IdempotencyKey(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldIdempotencyKey, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeliveredAt applies equality check predicate on the "delivered_at" field. It's identical to DeliveredAtEQ.
func DeliveredAt(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldDeliveredAt, v))
}

// EventIDEQ applies the EQ predicate on the "event_id" field.
func EventIDEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldEventID, v))
}

// EventIDNEQ applies the NEQ predicate on the "event_id" field.
func EventIDNEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldEventID, v))
}

// EventIDIn applies the In predicate on the "event_id" field.
func EventIDIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldEventID, vs...))
}

// EventIDNotIn applies the NotIn predicate on the "event_id" field.
func EventIDNotIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldEventID, vs...))
}

// EventIDGT applies the GT predicate on the "event_id" field.
func EventIDGT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldEventID, v))
}

// EventIDGTE applies the GTE predicate on the "event_id" field.
func EventIDGTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldEventID, v))
}

// EventIDLT applies the LT predicate on the "event_id" field.
func EventIDLT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldEventID, v))
}

// EventIDLTE applies the LTE predicate on the "event_id" field.
func EventIDLTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldEventID, v))
}

// RevisionEQ applies the EQ predicate on the "revision" field.
func RevisionEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldRevision, v))
}

// RevisionNEQ applies the NEQ predicate on the "revision" field.
func RevisionNEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldRevision, v))
}

// RevisionIn applies the In predicate on the "revision" field.
func RevisionIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldRevision, vs...))
}

// RevisionNotIn applies the NotIn predicate on the "revision" field.
func RevisionNotIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldRevision, vs...))
}

// KindEQ applies the EQ predicate on the "kind" field.
func KindEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldKind, v))
}

// KindNEQ applies the NEQ predicate on the "kind" field.
func KindNEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldKind, v))
}

// KindIn applies the In predicate on the "kind" field.
func KindIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldKind, vs...))
}

// KindNotIn applies the NotIn predicate on the "kind" field.
func KindNotIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldKind, vs...))
}

// KindGT applies the GT predicate on the "kind" field.
func KindGT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldKind, v))
}

// KindGTE applies the GTE predicate on the "kind" field.
func KindGTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldKind, v))
}

// KindLT applies the LT predicate on the "kind" field.
func KindLT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldKind, v))
}

// KindLTE applies the LTE predicate on the "kind" field.
func KindLTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldKind, v))
}

// KindContains applies the Contains predicate on the "kind" field.
func KindContains(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContains(FieldKind, v))
}

// KindHasPrefix applies the HasPrefix predicate on the "kind" field.
func KindHasPrefix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasPrefix(FieldKind, v))
}

// KindHasSuffix applies the HasSuffix predicate on the "kind" field.
func KindHasSuffix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasSuffix(FieldKind, v))
}

// KindEqualFold applies the EqualFold predicate on the "kind" field.
func KindEqualFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEqualFold(FieldKind, v))
}

// KindContainsFold applies the ContainsFold predicate on the "kind" field.
func KindContainsFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContainsFold(FieldKind, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContainsFold(FieldReason, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDIsNil applies the IsNil predicate on the "role_id" field.
func RoleIDIsNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIsNull(FieldRoleID))
}

// RoleIDNotNil applies the NotNil predicate on the "role_id" field.
func RoleIDNotNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotNull(FieldRoleID))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldUserID, v))
}

// UserIDIsNil applies the IsNil predicate on the "user_id" field.
func UserIDIsNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIsNull(FieldUserID))
}

// UserIDNotNil applies the NotNil predicate on the "user_id" field.
func UserIDNotNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotNull(FieldUserID))
}

// PermissionIDEQ applies the EQ predicate on the "permission_id" field.
func PermissionIDEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldPermissionID, v))
}

// PermissionIDNEQ applies the NEQ predicate on the "permission_id" field.
func PermissionIDNEQ(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldPermissionID, v))
}

// PermissionIDIn applies the In predicate on the "permission_id" field.
func PermissionIDIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldPermissionID, vs...))
}

// PermissionIDNotIn applies the NotIn predicate on the "permission_id" field.
func PermissionIDNotIn(vs ...uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldPermissionID, vs...))
}

// PermissionIDGT applies the GT predicate on the "permission_id" field.
func PermissionIDGT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldPermissionID, v))
}

// PermissionIDGTE applies the GTE predicate on the "permission_id" field.
func PermissionIDGTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldPermissionID, v))
}

// PermissionIDLT applies the LT predicate on the "permission_id" field.
func PermissionIDLT(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldPermissionID, v))
}

// PermissionIDLTE applies the LTE predicate on the "permission_id" field.
func PermissionIDLTE(v uuid.UUID) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldPermissionID, v))
}

// PermissionIDIsNil applies the IsNil predicate on the "permission_id" field.
func PermissionIDIsNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIsNull(FieldPermissionID))
}

// PermissionIDNotNil applies the NotNil predicate on the "permission_id" field.
func PermissionIDNotNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotNull(FieldPermissionID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContainsFold(FieldStatus, v))
}

// AttemptCountEQ applies the EQ predicate on the "attempt_count" field.
func AttemptCountEQ(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldAttemptCount, v))
}

// AttemptCountNEQ applies the NEQ predicate on the "attempt_count" field.
func AttemptCountNEQ(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldAttemptCount, v))
}

// AttemptCountIn applies the In predicate on the "attempt_count" field.
func AttemptCountIn(vs ...int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldAttemptCount, vs...))
}

// AttemptCountNotIn applies the NotIn predicate on the "attempt_count" field.
func AttemptCountNotIn(vs ...int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldAttemptCount, vs...))
}

// AttemptCountGT applies the GT predicate on the "attempt_count" field.
func AttemptCountGT(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldAttemptCount, v))
}

// AttemptCountGTE applies the GTE predicate on the "attempt_count" field.
func AttemptCountGTE(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldAttemptCount, v))
}

// AttemptCountLT applies the LT predicate on the "attempt_count" field.
func AttemptCountLT(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldAttemptCount, v))
}

// AttemptCountLTE applies the LTE predicate on the "attempt_count" field.
func AttemptCountLTE(v int) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldAttemptCount, v))
}

// NextAttemptAtEQ applies the EQ predicate on the "next_attempt_at" field.
func NextAttemptAtEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtNEQ applies the NEQ predicate on the "next_attempt_at" field.
func NextAttemptAtNEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldNextAttemptAt, v))
}

// NextAttemptAtIn applies the In predicate on the "next_attempt_at" field.
func NextAttemptAtIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtNotIn applies the NotIn predicate on the "next_attempt_at" field.
func NextAttemptAtNotIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldNextAttemptAt, vs...))
}

// NextAttemptAtGT applies the GT predicate on the "next_attempt_at" field.
func NextAttemptAtGT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldNextAttemptAt, v))
}

// NextAttemptAtGTE applies the GTE predicate on the "next_attempt_at" field.
func NextAttemptAtGTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldNextAttemptAt, v))
}

// NextAttemptAtLT applies the LT predicate on the "next_attempt_at" field.
func NextAttemptAtLT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldNextAttemptAt, v))
}

// NextAttemptAtLTE applies the LTE predicate on the "next_attempt_at" field.
func NextAttemptAtLTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldNextAttemptAt, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContainsFold(FieldLastError, v))
}

// IdempotencyKeyEQ applies the EQ predicate on the "idempotency_key" field.
func IdempotencyKeyEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyNEQ applies the NEQ predicate on the "idempotency_key" field.
func IdempotencyKeyNEQ(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldIdempotencyKey, v))
}

// IdempotencyKeyIn applies the In predicate on the "idempotency_key" field.
func IdempotencyKeyIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyNotIn applies the NotIn predicate on the "idempotency_key" field.
func IdempotencyKeyNotIn(vs ...string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldIdempotencyKey, vs...))
}

// IdempotencyKeyGT applies the GT predicate on the "idempotency_key" field.
func IdempotencyKeyGT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldIdempotencyKey, v))
}

// IdempotencyKeyGTE applies the GTE predicate on the "idempotency_key" field.
func IdempotencyKeyGTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyLT applies the LT predicate on the "idempotency_key" field.
func IdempotencyKeyLT(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldIdempotencyKey, v))
}

// IdempotencyKeyLTE applies the LTE predicate on the "idempotency_key" field.
func IdempotencyKeyLTE(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldIdempotencyKey, v))
}

// IdempotencyKeyContains applies the Contains predicate on the "idempotency_key" field.
func IdempotencyKeyContains(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContains(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasPrefix applies the HasPrefix predicate on the "idempotency_key" field.
func IdempotencyKeyHasPrefix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasPrefix(FieldIdempotencyKey, v))
}

// IdempotencyKeyHasSuffix applies the HasSuffix predicate on the "idempotency_key" field.
func IdempotencyKeyHasSuffix(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldHasSuffix(FieldIdempotencyKey, v))
}

// IdempotencyKeyEqualFold applies the EqualFold predicate on the "idempotency_key" field.
func IdempotencyKeyEqualFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEqualFold(FieldIdempotencyKey, v))
}

// IdempotencyKeyContainsFold applies the ContainsFold predicate on the "idempotency_key" field.
func IdempotencyKeyContainsFold(v string) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldContainsFold(FieldIdempotencyKey, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeliveredAtEQ applies the EQ predicate on the "delivered_at" field.
func DeliveredAtEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldEQ(FieldDeliveredAt, v))
}

// DeliveredAtNEQ applies the NEQ predicate on the "delivered_at" field.
func DeliveredAtNEQ(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNEQ(FieldDeliveredAt, v))
}

// DeliveredAtIn applies the In predicate on the "delivered_at" field.
func DeliveredAtIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIn(FieldDeliveredAt, vs...))
}

// DeliveredAtNotIn applies the NotIn predicate on the "delivered_at" field.
func DeliveredAtNotIn(vs ...int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotIn(FieldDeliveredAt, vs...))
}

// DeliveredAtGT applies the GT predicate on the "delivered_at" field.
func DeliveredAtGT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGT(FieldDeliveredAt, v))
}

// DeliveredAtGTE applies the GTE predicate on the "delivered_at" field.
func DeliveredAtGTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldGTE(FieldDeliveredAt, v))
}

// DeliveredAtLT applies the LT predicate on the "delivered_at" field.
func DeliveredAtLT(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLT(FieldDeliveredAt, v))
}

// DeliveredAtLTE applies the LTE predicate on the "delivered_at" field.
func DeliveredAtLTE(v int64) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldLTE(FieldDeliveredAt, v))
}

// DeliveredAtIsNil applies the IsNil predicate on the "delivered_at" field.
func DeliveredAtIsNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldIsNull(FieldDeliveredAt))
}

// DeliveredAtNotNil applies the NotNil predicate on the "delivered_at" field.
func DeliveredAtNotNil() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.FieldNotNull(FieldDeliveredAt))
}

// HasPolicyRevision applies the HasEdge predicate on the "policy_revision" edge.
func HasPolicyRevision() predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PolicyRevisionTable, PolicyRevisionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPolicyRevisionWith applies the HasEdge predicate on the "policy_revision" edge with a given conditions (other predicates).
func HasPolicyRevisionWith(preds ...predicate.RbacPolicyRevision) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(func(s *sql.Selector) {
		step := newPolicyRevisionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RbacPolicyOutboxEvent) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RbacPolicyOutboxEvent) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RbacPolicyOutboxEvent) predicate.RbacPolicyOutboxEvent {
	return predicate.RbacPolicyOutboxEvent(sql.NotPredicates(p))
}
