-- Create "permissions" table
CREATE TABLE "permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "permission_id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NOT NULL DEFAULT '',
  "module" character varying NOT NULL,
  "http_method" character varying NOT NULL,
  "path_template" character varying NOT NULL,
  "active" boolean NOT NULL DEFAULT true,
  "is_system" boolean NOT NULL DEFAULT false,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "permission_active_permission_id" to table: "permissions"
CREATE INDEX "permission_active_permission_id" ON "permissions" ("active", "permission_id");
-- Create index "permission_http_method_path_template" to table: "permissions"
CREATE UNIQUE INDEX "permission_http_method_path_template" ON "permissions" ("http_method", "path_template");
-- Create index "permission_http_method_permission_id" to table: "permissions"
CREATE INDEX "permission_http_method_permission_id" ON "permissions" ("http_method", "permission_id");
-- Create index "permission_is_system_permission_id" to table: "permissions"
CREATE INDEX "permission_is_system_permission_id" ON "permissions" ("is_system", "permission_id");
-- Create index "permission_module_permission_id" to table: "permissions"
CREATE INDEX "permission_module_permission_id" ON "permissions" ("module", "permission_id");
-- Create index "permissions_permission_id_key" to table: "permissions"
CREATE UNIQUE INDEX "permissions_permission_id_key" ON "permissions" ("permission_id");
-- Set comment to column: "id" on table: "permissions"
COMMENT ON COLUMN "permissions"."id" IS '权限ID';
-- Set comment to column: "permission_id" on table: "permissions"
COMMENT ON COLUMN "permissions"."permission_id" IS '外部权限ID';
-- Set comment to column: "name" on table: "permissions"
COMMENT ON COLUMN "permissions"."name" IS '权限名称';
-- Set comment to column: "description" on table: "permissions"
COMMENT ON COLUMN "permissions"."description" IS '权限说明';
-- Set comment to column: "module" on table: "permissions"
COMMENT ON COLUMN "permissions"."module" IS '权限所属模块';
-- Set comment to column: "http_method" on table: "permissions"
COMMENT ON COLUMN "permissions"."http_method" IS 'HTTP 方法';
-- Set comment to column: "path_template" on table: "permissions"
COMMENT ON COLUMN "permissions"."path_template" IS '路径模板';
-- Set comment to column: "active" on table: "permissions"
COMMENT ON COLUMN "permissions"."active" IS '权限是否启用';
-- Set comment to column: "is_system" on table: "permissions"
COMMENT ON COLUMN "permissions"."is_system" IS '是否系统权限';
-- Set comment to column: "created_at" on table: "permissions"
COMMENT ON COLUMN "permissions"."created_at" IS '创建时间戳毫秒';
-- Set comment to column: "updated_at" on table: "permissions"
COMMENT ON COLUMN "permissions"."updated_at" IS '更新时间戳毫秒';
-- Create "role_permissions" table
CREATE TABLE "role_permissions" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" bigint NOT NULL,
  "permission_id" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "rolepermission_permission_id_role_id" to table: "role_permissions"
CREATE INDEX "rolepermission_permission_id_role_id" ON "role_permissions" ("permission_id", "role_id");
-- Create index "rolepermission_role_id_permission_id" to table: "role_permissions"
CREATE UNIQUE INDEX "rolepermission_role_id_permission_id" ON "role_permissions" ("role_id", "permission_id");
-- Set comment to column: "id" on table: "role_permissions"
COMMENT ON COLUMN "role_permissions"."id" IS '角色权限绑定ID';
-- Set comment to column: "created_at" on table: "role_permissions"
COMMENT ON COLUMN "role_permissions"."created_at" IS '创建时间戳毫秒';
-- Set comment to column: "permission_id" on table: "role_permissions"
COMMENT ON COLUMN "role_permissions"."permission_id" IS '权限内部ID';
-- Set comment to column: "role_id" on table: "role_permissions"
COMMENT ON COLUMN "role_permissions"."role_id" IS '角色内部ID';
-- Create "roles" table
CREATE TABLE "roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "role_id" uuid NOT NULL,
  "name" character varying NOT NULL,
  "description" character varying NOT NULL DEFAULT '',
  "active" boolean NOT NULL DEFAULT true,
  "is_system" boolean NOT NULL DEFAULT false,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "role_active_role_id" to table: "roles"
CREATE INDEX "role_active_role_id" ON "roles" ("active", "role_id");
-- Create index "role_is_system_role_id" to table: "roles"
CREATE INDEX "role_is_system_role_id" ON "roles" ("is_system", "role_id");
-- Create index "roles_role_id_key" to table: "roles"
CREATE UNIQUE INDEX "roles_role_id_key" ON "roles" ("role_id");
-- Set comment to column: "id" on table: "roles"
COMMENT ON COLUMN "roles"."id" IS '角色ID';
-- Set comment to column: "role_id" on table: "roles"
COMMENT ON COLUMN "roles"."role_id" IS '外部角色ID';
-- Set comment to column: "name" on table: "roles"
COMMENT ON COLUMN "roles"."name" IS '角色名称';
-- Set comment to column: "description" on table: "roles"
COMMENT ON COLUMN "roles"."description" IS '角色说明';
-- Set comment to column: "active" on table: "roles"
COMMENT ON COLUMN "roles"."active" IS '角色是否启用';
-- Set comment to column: "is_system" on table: "roles"
COMMENT ON COLUMN "roles"."is_system" IS '是否系统角色';
-- Set comment to column: "created_at" on table: "roles"
COMMENT ON COLUMN "roles"."created_at" IS '创建时间戳毫秒';
-- Set comment to column: "updated_at" on table: "roles"
COMMENT ON COLUMN "roles"."updated_at" IS '更新时间戳毫秒';
-- Create "user_roles" table
CREATE TABLE "user_roles" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" bigint NOT NULL,
  "role_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "userrole_role_id_user_id" to table: "user_roles"
CREATE INDEX "userrole_role_id_user_id" ON "user_roles" ("role_id", "user_id");
-- Create index "userrole_user_id_role_id" to table: "user_roles"
CREATE UNIQUE INDEX "userrole_user_id_role_id" ON "user_roles" ("user_id", "role_id");
-- Set comment to column: "id" on table: "user_roles"
COMMENT ON COLUMN "user_roles"."id" IS '用户角色绑定ID';
-- Set comment to column: "created_at" on table: "user_roles"
COMMENT ON COLUMN "user_roles"."created_at" IS '创建时间戳毫秒';
-- Set comment to column: "role_id" on table: "user_roles"
COMMENT ON COLUMN "user_roles"."role_id" IS '角色内部ID';
-- Set comment to column: "user_id" on table: "user_roles"
COMMENT ON COLUMN "user_roles"."user_id" IS '用户内部ID';
-- Create "users" table
CREATE TABLE "users" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" uuid NOT NULL,
  "nickname" character varying NOT NULL,
  "username" character varying NOT NULL,
  "password_hash" character varying NOT NULL,
  "token_version" bigint NOT NULL DEFAULT 1,
  "status" bigint NOT NULL DEFAULT 100,
  "deleted_at" bigint NULL,
  "created_at" bigint NOT NULL,
  "updated_at" bigint NOT NULL,
  PRIMARY KEY ("id")
);
-- Create index "user_deleted_at" to table: "users"
CREATE INDEX "user_deleted_at" ON "users" ("deleted_at");
-- Create index "user_deleted_at_user_id" to table: "users"
CREATE INDEX "user_deleted_at_user_id" ON "users" ("deleted_at", "user_id");
-- Create index "user_status" to table: "users"
CREATE INDEX "user_status" ON "users" ("status");
-- Create index "user_status_deleted_at_user_id" to table: "users"
CREATE INDEX "user_status_deleted_at_user_id" ON "users" ("status", "deleted_at", "user_id");
-- Create index "users_nickname_trgm" to table: "users"
CREATE INDEX "users_nickname_trgm" ON "users" USING GIN ("nickname" gin_trgm_ops);
-- Create index "users_user_id_key" to table: "users"
CREATE UNIQUE INDEX "users_user_id_key" ON "users" ("user_id");
-- Create index "users_username_key" to table: "users"
CREATE UNIQUE INDEX "users_username_key" ON "users" ("username");
-- Set comment to column: "id" on table: "users"
COMMENT ON COLUMN "users"."id" IS '用户ID';
-- Set comment to column: "user_id" on table: "users"
COMMENT ON COLUMN "users"."user_id" IS '外部用户ID';
-- Set comment to column: "nickname" on table: "users"
COMMENT ON COLUMN "users"."nickname" IS '用户昵称';
-- Set comment to column: "username" on table: "users"
COMMENT ON COLUMN "users"."username" IS '用户名';
-- Set comment to column: "password_hash" on table: "users"
COMMENT ON COLUMN "users"."password_hash" IS '密码哈希';
-- Set comment to column: "token_version" on table: "users"
COMMENT ON COLUMN "users"."token_version" IS '认证令牌版本';
-- Set comment to column: "status" on table: "users"
COMMENT ON COLUMN "users"."status" IS '用户状态：100 正常，200 冻结/停用，300 必须修改密码';
-- Set comment to column: "deleted_at" on table: "users"
COMMENT ON COLUMN "users"."deleted_at" IS '软删除时间戳毫秒，NULL 表示未删除';
-- Set comment to column: "created_at" on table: "users"
COMMENT ON COLUMN "users"."created_at" IS '创建时间戳毫秒';
-- Set comment to column: "updated_at" on table: "users"
COMMENT ON COLUMN "users"."updated_at" IS '更新时间戳毫秒';
