-- Create "rbac_policy_revision_counters" table
CREATE TABLE "rbac_policy_revision_counters" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "last_revision" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Set comment to column: "id" on table: "rbac_policy_revision_counters"
COMMENT ON COLUMN "rbac_policy_revision_counters"."id" IS '固定 RBAC policy revision counter ID';
-- Set comment to column: "last_revision" on table: "rbac_policy_revision_counters"
COMMENT ON COLUMN "rbac_policy_revision_counters"."last_revision" IS '最近已分配的 RBAC policy revision';
-- 使用 migration 前已提交的最大 revision 初始化固定 counter 行。
INSERT INTO "rbac_policy_revision_counters" ("id", "last_revision")
SELECT 1, COALESCE(MAX("revision"), 0)
FROM "rbac_policy_revisions";
