-- Modify "rbac_policy_outbox_events" table
ALTER TABLE "rbac_policy_outbox_events" DROP COLUMN "revision", ADD COLUMN "policy_revision" bigint NULL, ADD COLUMN "user_role_revision" bigint NULL;
-- Create index "rbac_policy_outbox_events_policy_revision_key" to table: "rbac_policy_outbox_events"
CREATE UNIQUE INDEX "rbac_policy_outbox_events_policy_revision_key" ON "rbac_policy_outbox_events" ("policy_revision");
-- Create index "rbac_policy_outbox_events_user_role_revision_key" to table: "rbac_policy_outbox_events"
CREATE UNIQUE INDEX "rbac_policy_outbox_events_user_role_revision_key" ON "rbac_policy_outbox_events" ("user_role_revision");
-- Create index "rbacpolicyoutboxevent_status_claimed_until_policy_revision_user" to table: "rbac_policy_outbox_events"
CREATE INDEX "rbacpolicyoutboxevent_status_claimed_until_policy_revision_user" ON "rbac_policy_outbox_events" ("status", "claimed_until", "policy_revision", "user_role_revision");
-- Create index "rbacpolicyoutboxevent_status_next_attempt_at_policy_revision_us" to table: "rbac_policy_outbox_events"
CREATE INDEX "rbacpolicyoutboxevent_status_next_attempt_at_policy_revision_us" ON "rbac_policy_outbox_events" ("status", "next_attempt_at", "policy_revision", "user_role_revision");
-- Set comment to column: "policy_revision" on table: "rbac_policy_outbox_events"
COMMENT ON COLUMN "rbac_policy_outbox_events"."policy_revision" IS '关联的 RBAC policy revision';
-- Set comment to column: "user_role_revision" on table: "rbac_policy_outbox_events"
COMMENT ON COLUMN "rbac_policy_outbox_events"."user_role_revision" IS '关联的 RBAC user-role revision';
-- Modify "rbac_policy_revisions" table
ALTER TABLE "rbac_policy_revisions" DROP COLUMN "user_id";
-- Create "rbac_user_role_revision_counters" table
CREATE TABLE "rbac_user_role_revision_counters" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "last_revision" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Set comment to column: "id" on table: "rbac_user_role_revision_counters"
COMMENT ON COLUMN "rbac_user_role_revision_counters"."id" IS '固定 RBAC user-role revision counter ID';
-- Set comment to column: "last_revision" on table: "rbac_user_role_revision_counters"
COMMENT ON COLUMN "rbac_user_role_revision_counters"."last_revision" IS '最近已分配的 RBAC user-role revision';
-- Create "rbac_user_role_revisions" table
CREATE TABLE "rbac_user_role_revisions" (
  "revision" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" bigint NOT NULL,
  "reason" character varying NOT NULL,
  "user_id" uuid NOT NULL,
  "role_id" uuid NULL,
  PRIMARY KEY ("revision")
);
-- Set comment to column: "revision" on table: "rbac_user_role_revisions"
COMMENT ON COLUMN "rbac_user_role_revisions"."revision" IS '单调递增的 RBAC user-role revision';
-- Set comment to column: "created_at" on table: "rbac_user_role_revisions"
COMMENT ON COLUMN "rbac_user_role_revisions"."created_at" IS '创建时间戳毫秒';
-- Set comment to column: "reason" on table: "rbac_user_role_revisions"
COMMENT ON COLUMN "rbac_user_role_revisions"."reason" IS '触发用户角色缓存失效的稳定原因';
-- Set comment to column: "user_id" on table: "rbac_user_role_revisions"
COMMENT ON COLUMN "rbac_user_role_revisions"."user_id" IS '相关外部用户ID';
-- Set comment to column: "role_id" on table: "rbac_user_role_revisions"
COMMENT ON COLUMN "rbac_user_role_revisions"."role_id" IS '相关外部角色ID';
