// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/auth/application (interfaces: UserTokenVersionStore,TokenVersionCache,RefreshSessionStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=sessions github.com/aegiscore/user-service/internal/features/auth/application UserTokenVersionStore,TokenVersionCache,RefreshSessionStore
//

// Package sessions is a generated GoMock package.
package sessions

import (
	context "context"
	reflect "reflect"
	time "time"

	domain "github.com/aegiscore/user-service/internal/features/auth/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserTokenVersionStore is a mock of UserTokenVersionStore interface.
type MockUserTokenVersionStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserTokenVersionStoreMockRecorder
	isgomock struct{}
}

// MockUserTokenVersionStoreMockRecorder is the mock recorder for MockUserTokenVersionStore.
type MockUserTokenVersionStoreMockRecorder struct {
	mock *MockUserTokenVersionStore
}

// NewMockUserTokenVersionStore creates a new mock instance.
func NewMockUserTokenVersionStore(ctrl *gomock.Controller) *MockUserTokenVersionStore {
	mock := &MockUserTokenVersionStore{ctrl: ctrl}
	mock.recorder = &MockUserTokenVersionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserTokenVersionStore) EXPECT() *MockUserTokenVersionStoreMockRecorder {
	return m.recorder
}

// GetTokenVersion mocks base method.
func (m *MockUserTokenVersionStore) GetTokenVersion(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTokenVersion indicates an expected call of GetTokenVersion.
func (mr *MockUserTokenVersionStoreMockRecorder) GetTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTokenVersion", reflect.TypeOf((*MockUserTokenVersionStore)(nil).GetTokenVersion), ctx, userID)
}

// IncrementTokenVersion mocks base method.
func (m *MockUserTokenVersionStore) IncrementTokenVersion(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IncrementTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IncrementTokenVersion indicates an expected call of IncrementTokenVersion.
func (mr *MockUserTokenVersionStoreMockRecorder) IncrementTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncrementTokenVersion", reflect.TypeOf((*MockUserTokenVersionStore)(nil).IncrementTokenVersion), ctx, userID)
}

// MockTokenVersionCache is a mock of TokenVersionCache interface.
type MockTokenVersionCache struct {
	ctrl     *gomock.Controller
	recorder *MockTokenVersionCacheMockRecorder
	isgomock struct{}
}

// MockTokenVersionCacheMockRecorder is the mock recorder for MockTokenVersionCache.
type MockTokenVersionCacheMockRecorder struct {
	mock *MockTokenVersionCache
}

// NewMockTokenVersionCache creates a new mock instance.
func NewMockTokenVersionCache(ctrl *gomock.Controller) *MockTokenVersionCache {
	mock := &MockTokenVersionCache{ctrl: ctrl}
	mock.recorder = &MockTokenVersionCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenVersionCache) EXPECT() *MockTokenVersionCacheMockRecorder {
	return m.recorder
}

// CacheTokenVersion mocks base method.
func (m *MockTokenVersionCache) CacheTokenVersion(ctx context.Context, userID string, tokenVersion int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CacheTokenVersion", ctx, userID, tokenVersion)
	ret0, _ := ret[0].(error)
	return ret0
}

// CacheTokenVersion indicates an expected call of CacheTokenVersion.
func (mr *MockTokenVersionCacheMockRecorder) CacheTokenVersion(ctx, userID, tokenVersion any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheTokenVersion", reflect.TypeOf((*MockTokenVersionCache)(nil).CacheTokenVersion), ctx, userID, tokenVersion)
}

// DeleteCachedTokenVersion mocks base method.
func (m *MockTokenVersionCache) DeleteCachedTokenVersion(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCachedTokenVersion", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCachedTokenVersion indicates an expected call of DeleteCachedTokenVersion.
func (mr *MockTokenVersionCacheMockRecorder) DeleteCachedTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCachedTokenVersion", reflect.TypeOf((*MockTokenVersionCache)(nil).DeleteCachedTokenVersion), ctx, userID)
}

// GetCachedTokenVersion mocks base method.
func (m *MockTokenVersionCache) GetCachedTokenVersion(ctx context.Context, userID string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedTokenVersion", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCachedTokenVersion indicates an expected call of GetCachedTokenVersion.
func (mr *MockTokenVersionCacheMockRecorder) GetCachedTokenVersion(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedTokenVersion", reflect.TypeOf((*MockTokenVersionCache)(nil).GetCachedTokenVersion), ctx, userID)
}

// MockRefreshSessionStore is a mock of RefreshSessionStore interface.
type MockRefreshSessionStore struct {
	ctrl     *gomock.Controller
	recorder *MockRefreshSessionStoreMockRecorder
	isgomock struct{}
}

// MockRefreshSessionStoreMockRecorder is the mock recorder for MockRefreshSessionStore.
type MockRefreshSessionStoreMockRecorder struct {
	mock *MockRefreshSessionStore
}

// NewMockRefreshSessionStore creates a new mock instance.
func NewMockRefreshSessionStore(ctrl *gomock.Controller) *MockRefreshSessionStore {
	mock := &MockRefreshSessionStore{ctrl: ctrl}
	mock.recorder = &MockRefreshSessionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRefreshSessionStore) EXPECT() *MockRefreshSessionStoreMockRecorder {
	return m.recorder
}

// CreateSession mocks base method.
func (m *MockRefreshSessionStore) CreateSession(ctx context.Context, session domain.AuthSession, ttl time.Duration, maxActiveSessionsPerUser int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", ctx, session, ttl, maxActiveSessionsPerUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockRefreshSessionStoreMockRecorder) CreateSession(ctx, session, ttl, maxActiveSessionsPerUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockRefreshSessionStore)(nil).CreateSession), ctx, session, ttl, maxActiveSessionsPerUser)
}

// DeleteAllUserSessions mocks base method.
func (m *MockRefreshSessionStore) DeleteAllUserSessions(ctx context.Context, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllUserSessions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllUserSessions indicates an expected call of DeleteAllUserSessions.
func (mr *MockRefreshSessionStoreMockRecorder) DeleteAllUserSessions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllUserSessions", reflect.TypeOf((*MockRefreshSessionStore)(nil).DeleteAllUserSessions), ctx, userID)
}

// DeleteSession mocks base method.
func (m *MockRefreshSessionStore) DeleteSession(ctx context.Context, userID, sessionID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockRefreshSessionStoreMockRecorder) DeleteSession(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockRefreshSessionStore)(nil).DeleteSession), ctx, userID, sessionID)
}

// GetSession mocks base method.
func (m *MockRefreshSessionStore) GetSession(ctx context.Context, userID, sessionID string) (domain.AuthSession, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", ctx, userID, sessionID)
	ret0, _ := ret[0].(domain.AuthSession)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockRefreshSessionStoreMockRecorder) GetSession(ctx, userID, sessionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockRefreshSessionStore)(nil).GetSession), ctx, userID, sessionID)
}

// RotateSession mocks base method.
func (m *MockRefreshSessionStore) RotateSession(ctx context.Context, oldSession, newSession domain.AuthSession, ttl time.Duration, maxActiveSessionsPerUser int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateSession", ctx, oldSession, newSession, ttl, maxActiveSessionsPerUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// RotateSession indicates an expected call of RotateSession.
func (mr *MockRefreshSessionStoreMockRecorder) RotateSession(ctx, oldSession, newSession, ttl, maxActiveSessionsPerUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateSession", reflect.TypeOf((*MockRefreshSessionStore)(nil).RotateSession), ctx, oldSession, newSession, ttl, maxActiveSessionsPerUser)
}
