// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/permission/application (interfaces: PermissionStore,RouteCatalogScanner,Metrics)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=query github.com/aegiscore/user-service/internal/features/permission/application PermissionStore,RouteCatalogScanner,Metrics
//

// Package query is a generated GoMock package.
package query

import (
	context "context"
	reflect "reflect"

	application "github.com/aegiscore/user-service/internal/features/permission/application"
	domain "github.com/aegiscore/user-service/internal/features/permission/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionStore is a mock of PermissionStore interface.
type MockPermissionStore struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionStoreMockRecorder
	isgomock struct{}
}

// MockPermissionStoreMockRecorder is the mock recorder for MockPermissionStore.
type MockPermissionStoreMockRecorder struct {
	mock *MockPermissionStore
}

// NewMockPermissionStore creates a new mock instance.
func NewMockPermissionStore(ctrl *gomock.Controller) *MockPermissionStore {
	mock := &MockPermissionStore{ctrl: ctrl}
	mock.recorder = &MockPermissionStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionStore) EXPECT() *MockPermissionStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPermissionStore) Create(ctx context.Context, input application.CreatePermissionInput) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPermissionStoreMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPermissionStore)(nil).Create), ctx, input)
}

// GetByPermissionID mocks base method.
func (m *MockPermissionStore) GetByPermissionID(ctx context.Context, permissionID uuid.UUID) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPermissionID", ctx, permissionID)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPermissionID indicates an expected call of GetByPermissionID.
func (mr *MockPermissionStoreMockRecorder) GetByPermissionID(ctx, permissionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPermissionID", reflect.TypeOf((*MockPermissionStore)(nil).GetByPermissionID), ctx, permissionID)
}

// List mocks base method.
func (m *MockPermissionStore) List(ctx context.Context, input application.ListPermissionsInput) ([]domain.Permission, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, input)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockPermissionStoreMockRecorder) List(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPermissionStore)(nil).List), ctx, input)
}

// ListAll mocks base method.
func (m *MockPermissionStore) ListAll(ctx context.Context) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockPermissionStoreMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockPermissionStore)(nil).ListAll), ctx)
}

// ListEffectiveByUserID mocks base method.
func (m *MockPermissionStore) ListEffectiveByUserID(ctx context.Context, userID uuid.UUID) ([]domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEffectiveByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEffectiveByUserID indicates an expected call of ListEffectiveByUserID.
func (mr *MockPermissionStoreMockRecorder) ListEffectiveByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEffectiveByUserID", reflect.TypeOf((*MockPermissionStore)(nil).ListEffectiveByUserID), ctx, userID)
}

// SetActive mocks base method.
func (m *MockPermissionStore) SetActive(ctx context.Context, permissionID uuid.UUID, active bool) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, permissionID, active)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetActive indicates an expected call of SetActive.
func (mr *MockPermissionStoreMockRecorder) SetActive(ctx, permissionID, active any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockPermissionStore)(nil).SetActive), ctx, permissionID, active)
}

// Update mocks base method.
func (m *MockPermissionStore) Update(ctx context.Context, input application.UpdatePermissionInput) (*domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPermissionStoreMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPermissionStore)(nil).Update), ctx, input)
}

// MockRouteCatalogScanner is a mock of RouteCatalogScanner interface.
type MockRouteCatalogScanner struct {
	ctrl     *gomock.Controller
	recorder *MockRouteCatalogScannerMockRecorder
	isgomock struct{}
}

// MockRouteCatalogScannerMockRecorder is the mock recorder for MockRouteCatalogScanner.
type MockRouteCatalogScannerMockRecorder struct {
	mock *MockRouteCatalogScanner
}

// NewMockRouteCatalogScanner creates a new mock instance.
func NewMockRouteCatalogScanner(ctrl *gomock.Controller) *MockRouteCatalogScanner {
	mock := &MockRouteCatalogScanner{ctrl: ctrl}
	mock.recorder = &MockRouteCatalogScannerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouteCatalogScanner) EXPECT() *MockRouteCatalogScannerMockRecorder {
	return m.recorder
}

// DiscoverRoutes mocks base method.
func (m *MockRouteCatalogScanner) DiscoverRoutes(ctx context.Context) ([]application.DiscoveredRoute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscoverRoutes", ctx)
	ret0, _ := ret[0].([]application.DiscoveredRoute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiscoverRoutes indicates an expected call of DiscoverRoutes.
func (mr *MockRouteCatalogScannerMockRecorder) DiscoverRoutes(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscoverRoutes", reflect.TypeOf((*MockRouteCatalogScanner)(nil).DiscoverRoutes), ctx)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// PolicyPublishFailed mocks base method.
func (m *MockMetrics) PolicyPublishFailed(ctx context.Context, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyPublishFailed", ctx, reason)
}

// PolicyPublishFailed indicates an expected call of PolicyPublishFailed.
func (mr *MockMetricsMockRecorder) PolicyPublishFailed(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyPublishFailed", reflect.TypeOf((*MockMetrics)(nil).PolicyPublishFailed), ctx, reason)
}

// PolicyPublishSucceeded mocks base method.
func (m *MockMetrics) PolicyPublishSucceeded(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyPublishSucceeded", ctx)
}

// PolicyPublishSucceeded indicates an expected call of PolicyPublishSucceeded.
func (mr *MockMetricsMockRecorder) PolicyPublishSucceeded(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyPublishSucceeded", reflect.TypeOf((*MockMetrics)(nil).PolicyPublishSucceeded), ctx)
}

// PolicyReloadFailed mocks base method.
func (m *MockMetrics) PolicyReloadFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadFailed", ctx, source, reason)
}

// PolicyReloadFailed indicates an expected call of PolicyReloadFailed.
func (mr *MockMetricsMockRecorder) PolicyReloadFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadFailed", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadFailed), ctx, source, reason)
}

// PolicyReloadSucceeded mocks base method.
func (m *MockMetrics) PolicyReloadSucceeded(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadSucceeded", ctx, source)
}

// PolicyReloadSucceeded indicates an expected call of PolicyReloadSucceeded.
func (mr *MockMetricsMockRecorder) PolicyReloadSucceeded(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadSucceeded", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadSucceeded), ctx, source)
}

// RouteDiffObserved mocks base method.
func (m *MockMetrics) RouteDiffObserved(ctx context.Context, missing, stale int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RouteDiffObserved", ctx, missing, stale)
}

// RouteDiffObserved indicates an expected call of RouteDiffObserved.
func (mr *MockMetricsMockRecorder) RouteDiffObserved(ctx, missing, stale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteDiffObserved", reflect.TypeOf((*MockMetrics)(nil).RouteDiffObserved), ctx, missing, stale)
}

// WatcherCheckFailed mocks base method.
func (m *MockMetrics) WatcherCheckFailed(ctx context.Context, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherCheckFailed", ctx, reason)
}

// WatcherCheckFailed indicates an expected call of WatcherCheckFailed.
func (mr *MockMetricsMockRecorder) WatcherCheckFailed(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherCheckFailed", reflect.TypeOf((*MockMetrics)(nil).WatcherCheckFailed), ctx, reason)
}

// WatcherReloadFailed mocks base method.
func (m *MockMetrics) WatcherReloadFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherReloadFailed", ctx, source, reason)
}

// WatcherReloadFailed indicates an expected call of WatcherReloadFailed.
func (mr *MockMetricsMockRecorder) WatcherReloadFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherReloadFailed", reflect.TypeOf((*MockMetrics)(nil).WatcherReloadFailed), ctx, source, reason)
}

// WatcherReloadSucceeded mocks base method.
func (m *MockMetrics) WatcherReloadSucceeded(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherReloadSucceeded", ctx, source)
}

// WatcherReloadSucceeded indicates an expected call of WatcherReloadSucceeded.
func (mr *MockMetricsMockRecorder) WatcherReloadSucceeded(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherReloadSucceeded", reflect.TypeOf((*MockMetrics)(nil).WatcherReloadSucceeded), ctx, source)
}

// WatcherVersionMismatch mocks base method.
func (m *MockMetrics) WatcherVersionMismatch(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherVersionMismatch", ctx, source)
}

// WatcherVersionMismatch indicates an expected call of WatcherVersionMismatch.
func (mr *MockMetricsMockRecorder) WatcherVersionMismatch(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherVersionMismatch", reflect.TypeOf((*MockMetrics)(nil).WatcherVersionMismatch), ctx, source)
}
