// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/user/application (interfaces: UserProfileStore)
//
// Generated by this command:
//
//	mockgen -destination=mock_test.go -package=command github.com/aegiscore/user-service/internal/features/user/application UserProfileStore
//

// Package command is a generated GoMock package.
package command

import (
	context "context"
	reflect "reflect"

	application "github.com/aegiscore/user-service/internal/features/user/application"
	domain "github.com/aegiscore/user-service/internal/features/user/domain"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserProfileStore is a mock of UserProfileStore interface.
type MockUserProfileStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserProfileStoreMockRecorder
	isgomock struct{}
}

// MockUserProfileStoreMockRecorder is the mock recorder for MockUserProfileStore.
type MockUserProfileStoreMockRecorder struct {
	mock *MockUserProfileStore
}

// NewMockUserProfileStore creates a new mock instance.
func NewMockUserProfileStore(ctrl *gomock.Controller) *MockUserProfileStore {
	mock := &MockUserProfileStore{ctrl: ctrl}
	mock.recorder = &MockUserProfileStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserProfileStore) EXPECT() *MockUserProfileStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserProfileStore) Create(ctx context.Context, input application.CreateUserInput) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, input)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUserProfileStoreMockRecorder) Create(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserProfileStore)(nil).Create), ctx, input)
}

// GetByUserID mocks base method.
func (m *MockUserProfileStore) GetByUserID(ctx context.Context, userID uuid.UUID) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockUserProfileStoreMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockUserProfileStore)(nil).GetByUserID), ctx, userID)
}

// ListUsers mocks base method.
func (m *MockUserProfileStore) ListUsers(ctx context.Context, input application.ListUsersInput) ([]domain.User, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", ctx, input)
	ret0, _ := ret[0].([]domain.User)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockUserProfileStoreMockRecorder) ListUsers(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockUserProfileStore)(nil).ListUsers), ctx, input)
}
