// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/aegiscore/user-service/ent/permission"
	"github.com/aegiscore/user-service/ent/rolepermission"
	"github.com/google/uuid"
)

// PermissionCreate is the builder for creating a Permission entity.
type PermissionCreate struct {
	config
	mutation *PermissionMutation
	hooks    []Hook
}

// SetPermissionID sets the "permission_id" field.
func (_c *PermissionCreate) SetPermissionID(v uuid.UUID) *PermissionCreate {
	_c.mutation.SetPermissionID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *PermissionCreate) SetName(v string) *PermissionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *PermissionCreate) SetDescription(v string) *PermissionCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableDescription(v *string) *PermissionCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetModule sets the "module" field.
func (_c *PermissionCreate) SetModule(v string) *PermissionCreate {
	_c.mutation.SetModule(v)
	return _c
}

// SetHTTPMethod sets the "http_method" field.
func (_c *PermissionCreate) SetHTTPMethod(v string) *PermissionCreate {
	_c.mutation.SetHTTPMethod(v)
	return _c
}

// SetPathTemplate sets the "path_template" field.
func (_c *PermissionCreate) SetPathTemplate(v string) *PermissionCreate {
	_c.mutation.SetPathTemplate(v)
	return _c
}

// SetActive sets the "active" field.
func (_c *PermissionCreate) SetActive(v bool) *PermissionCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableActive(v *bool) *PermissionCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetIsSystem sets the "is_system" field.
func (_c *PermissionCreate) SetIsSystem(v bool) *PermissionCreate {
	_c.mutation.SetIsSystem(v)
	return _c
}

// SetNillableIsSystem sets the "is_system" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableIsSystem(v *bool) *PermissionCreate {
	if v != nil {
		_c.SetIsSystem(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PermissionCreate) SetCreatedAt(v int64) *PermissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableCreatedAt(v *int64) *PermissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PermissionCreate) SetUpdatedAt(v int64) *PermissionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PermissionCreate) SetNillableUpdatedAt(v *int64) *PermissionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PermissionCreate) SetID(v int64) *PermissionCreate {
	_c.mutation.SetID(v)
	return _c
}

// AddRolePermissionIDs adds the "role_permissions" edge to the RolePermission entity by IDs.
func (_c *PermissionCreate) AddRolePermissionIDs(ids ...int64) *PermissionCreate {
	_c.mutation.AddRolePermissionIDs(ids...)
	return _c
}

// AddRolePermissions adds the "role_permissions" edges to the RolePermission entity.
func (_c *PermissionCreate) AddRolePermissions(v ...*RolePermission) *PermissionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRolePermissionIDs(ids...)
}

// Mutation returns the PermissionMutation object of the builder.
func (_c *PermissionCreate) Mutation() *PermissionMutation {
	return _c.mutation
}

// Save creates the Permission in the database.
func (_c *PermissionCreate) Save(ctx context.Context) (*Permission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PermissionCreate) SaveX(ctx context.Context) *Permission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PermissionCreate) defaults() {
	if _, ok := _c.mutation.Description(); !ok {
		v := permission.DefaultDescription
		_c.mutation.SetDescription(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := permission.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		v := permission.DefaultIsSystem
		_c.mutation.SetIsSystem(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := permission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := permission.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PermissionCreate) check() error {
	if _, ok := _c.mutation.PermissionID(); !ok {
		return &ValidationError{Name: "permission_id", err: errors.New(`ent: missing required field "Permission.permission_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Permission.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := permission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Permission.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Permission.description"`)}
	}
	if v, ok := _c.mutation.Description(); ok {
		if err := permission.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "Permission.description": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Module(); !ok {
		return &ValidationError{Name: "module", err: errors.New(`ent: missing required field "Permission.module"`)}
	}
	if v, ok := _c.mutation.Module(); ok {
		if err := permission.ModuleValidator(v); err != nil {
			return &ValidationError{Name: "module", err: fmt.Errorf(`ent: validator failed for field "Permission.module": %w`, err)}
		}
	}
	if _, ok := _c.mutation.HTTPMethod(); !ok {
		return &ValidationError{Name: "http_method", err: errors.New(`ent: missing required field "Permission.http_method"`)}
	}
	if v, ok := _c.mutation.HTTPMethod(); ok {
		if err := permission.HTTPMethodValidator(v); err != nil {
			return &ValidationError{Name: "http_method", err: fmt.Errorf(`ent: validator failed for field "Permission.http_method": %w`, err)}
		}
	}
	if _, ok := _c.mutation.PathTemplate(); !ok {
		return &ValidationError{Name: "path_template", err: errors.New(`ent: missing required field "Permission.path_template"`)}
	}
	if v, ok := _c.mutation.PathTemplate(); ok {
		if err := permission.PathTemplateValidator(v); err != nil {
			return &ValidationError{Name: "path_template", err: fmt.Errorf(`ent: validator failed for field "Permission.path_template": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Permission.active"`)}
	}
	if _, ok := _c.mutation.IsSystem(); !ok {
		return &ValidationError{Name: "is_system", err: errors.New(`ent: missing required field "Permission.is_system"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Permission.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Permission.updated_at"`)}
	}
	return nil
}

func (_c *PermissionCreate) sqlSave(ctx context.Context) (*Permission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PermissionCreate) createSpec() (*Permission, *sqlgraph.CreateSpec) {
	var (
		_node = &Permission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(permission.Table, sqlgraph.NewFieldSpec(permission.FieldID, field.TypeInt64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.PermissionID(); ok {
		_spec.SetField(permission.FieldPermissionID, field.TypeUUID, value)
		_node.PermissionID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(permission.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(permission.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Module(); ok {
		_spec.SetField(permission.FieldModule, field.TypeString, value)
		_node.Module = value
	}
	if value, ok := _c.mutation.HTTPMethod(); ok {
		_spec.SetField(permission.FieldHTTPMethod, field.TypeString, value)
		_node.HTTPMethod = value
	}
	if value, ok := _c.mutation.PathTemplate(); ok {
		_spec.SetField(permission.FieldPathTemplate, field.TypeString, value)
		_node.PathTemplate = value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(permission.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.IsSystem(); ok {
		_spec.SetField(permission.FieldIsSystem, field.TypeBool, value)
		_node.IsSystem = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(permission.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(permission.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RolePermissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   permission.RolePermissionsTable,
			Columns: []string{permission.RolePermissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(rolepermission.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PermissionCreateBulk is the builder for creating many Permission entities in bulk.
type PermissionCreateBulk struct {
	config
	err      error
	builders []*PermissionCreate
}

// Save creates the Permission entities in the database.
func (_c *PermissionCreateBulk) Save(ctx context.Context) ([]*Permission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Permission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PermissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PermissionCreateBulk) SaveX(ctx context.Context) []*Permission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PermissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PermissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
