// Code generated by ent, DO NOT EDIT.

package rbacuserrolerevision

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/aegiscore/user-service/internal/persistence/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldReason, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldUserID, v))
}

// RoleID applies equality check predicate on the "role_id" field. It's identical to RoleIDEQ.
func RoleID(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldRoleID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLTE(FieldCreatedAt, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldContainsFold(FieldReason, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLTE(FieldUserID, v))
}

// RoleIDEQ applies the EQ predicate on the "role_id" field.
func RoleIDEQ(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldEQ(FieldRoleID, v))
}

// RoleIDNEQ applies the NEQ predicate on the "role_id" field.
func RoleIDNEQ(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNEQ(FieldRoleID, v))
}

// RoleIDIn applies the In predicate on the "role_id" field.
func RoleIDIn(vs ...uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldIn(FieldRoleID, vs...))
}

// RoleIDNotIn applies the NotIn predicate on the "role_id" field.
func RoleIDNotIn(vs ...uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNotIn(FieldRoleID, vs...))
}

// RoleIDGT applies the GT predicate on the "role_id" field.
func RoleIDGT(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGT(FieldRoleID, v))
}

// RoleIDGTE applies the GTE predicate on the "role_id" field.
func RoleIDGTE(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldGTE(FieldRoleID, v))
}

// RoleIDLT applies the LT predicate on the "role_id" field.
func RoleIDLT(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLT(FieldRoleID, v))
}

// RoleIDLTE applies the LTE predicate on the "role_id" field.
func RoleIDLTE(v uuid.UUID) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldLTE(FieldRoleID, v))
}

// RoleIDIsNil applies the IsNil predicate on the "role_id" field.
func RoleIDIsNil() predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldIsNull(FieldRoleID))
}

// RoleIDNotNil applies the NotNil predicate on the "role_id" field.
func RoleIDNotNil() predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.FieldNotNull(FieldRoleID))
}

// HasOutboxEvent applies the HasEdge predicate on the "outbox_event" edge.
func HasOutboxEvent() predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, OutboxEventTable, OutboxEventColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOutboxEventWith applies the HasEdge predicate on the "outbox_event" edge with a given conditions (other predicates).
func HasOutboxEventWith(preds ...predicate.RbacPolicyOutboxEvent) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(func(s *sql.Selector) {
		step := newOutboxEventStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RbacUserRoleRevision) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RbacUserRoleRevision) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RbacUserRoleRevision) predicate.RbacUserRoleRevision {
	return predicate.RbacUserRoleRevision(sql.NotPredicates(p))
}
