// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/permission/application (interfaces: PolicyReloadEngine,PolicyVersionPublisher,PolicyVersionTracker,Metrics)
//
// Generated by this command:
//
//	mockgen -destination=mock_policy_sync_test.go -package=application github.com/aegiscore/user-service/internal/features/permission/application PolicyReloadEngine,PolicyVersionPublisher,PolicyVersionTracker,Metrics
//

// Package application is a generated GoMock package.
package application

import (
	context "context"
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyReloadEngine is a mock of PolicyReloadEngine interface.
type MockPolicyReloadEngine struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyReloadEngineMockRecorder
	isgomock struct{}
}

// MockPolicyReloadEngineMockRecorder is the mock recorder for MockPolicyReloadEngine.
type MockPolicyReloadEngineMockRecorder struct {
	mock *MockPolicyReloadEngine
}

// NewMockPolicyReloadEngine creates a new mock instance.
func NewMockPolicyReloadEngine(ctrl *gomock.Controller) *MockPolicyReloadEngine {
	mock := &MockPolicyReloadEngine{ctrl: ctrl}
	mock.recorder = &MockPolicyReloadEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyReloadEngine) EXPECT() *MockPolicyReloadEngineMockRecorder {
	return m.recorder
}

// InvalidateAllUserRoles mocks base method.
func (m *MockPolicyReloadEngine) InvalidateAllUserRoles() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateAllUserRoles")
}

// InvalidateAllUserRoles indicates an expected call of InvalidateAllUserRoles.
func (mr *MockPolicyReloadEngineMockRecorder) InvalidateAllUserRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllUserRoles", reflect.TypeOf((*MockPolicyReloadEngine)(nil).InvalidateAllUserRoles))
}

// InvalidateUserRole mocks base method.
func (m *MockPolicyReloadEngine) InvalidateUserRole(userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateUserRole", userID)
}

// InvalidateUserRole indicates an expected call of InvalidateUserRole.
func (mr *MockPolicyReloadEngineMockRecorder) InvalidateUserRole(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserRole", reflect.TypeOf((*MockPolicyReloadEngine)(nil).InvalidateUserRole), userID)
}

// Reload mocks base method.
func (m *MockPolicyReloadEngine) Reload(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockPolicyReloadEngineMockRecorder) Reload(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockPolicyReloadEngine)(nil).Reload), ctx)
}

// MockPolicyVersionPublisher is a mock of PolicyVersionPublisher interface.
type MockPolicyVersionPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyVersionPublisherMockRecorder
	isgomock struct{}
}

// MockPolicyVersionPublisherMockRecorder is the mock recorder for MockPolicyVersionPublisher.
type MockPolicyVersionPublisherMockRecorder struct {
	mock *MockPolicyVersionPublisher
}

// NewMockPolicyVersionPublisher creates a new mock instance.
func NewMockPolicyVersionPublisher(ctrl *gomock.Controller) *MockPolicyVersionPublisher {
	mock := &MockPolicyVersionPublisher{ctrl: ctrl}
	mock.recorder = &MockPolicyVersionPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyVersionPublisher) EXPECT() *MockPolicyVersionPublisherMockRecorder {
	return m.recorder
}

// PublishPolicyChanged mocks base method.
func (m *MockPolicyVersionPublisher) PublishPolicyChanged(ctx context.Context, change PolicyChange) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishPolicyChanged", ctx, change)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishPolicyChanged indicates an expected call of PublishPolicyChanged.
func (mr *MockPolicyVersionPublisherMockRecorder) PublishPolicyChanged(ctx, change any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishPolicyChanged", reflect.TypeOf((*MockPolicyVersionPublisher)(nil).PublishPolicyChanged), ctx, change)
}

// MockPolicyVersionTracker is a mock of PolicyVersionTracker interface.
type MockPolicyVersionTracker struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyVersionTrackerMockRecorder
	isgomock struct{}
}

// MockPolicyVersionTrackerMockRecorder is the mock recorder for MockPolicyVersionTracker.
type MockPolicyVersionTrackerMockRecorder struct {
	mock *MockPolicyVersionTracker
}

// NewMockPolicyVersionTracker creates a new mock instance.
func NewMockPolicyVersionTracker(ctrl *gomock.Controller) *MockPolicyVersionTracker {
	mock := &MockPolicyVersionTracker{ctrl: ctrl}
	mock.recorder = &MockPolicyVersionTrackerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyVersionTracker) EXPECT() *MockPolicyVersionTrackerMockRecorder {
	return m.recorder
}

// Applied mocks base method.
func (m *MockPolicyVersionTracker) Applied() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Applied")
	ret0, _ := ret[0].(int64)
	return ret0
}

// Applied indicates an expected call of Applied.
func (mr *MockPolicyVersionTrackerMockRecorder) Applied() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Applied", reflect.TypeOf((*MockPolicyVersionTracker)(nil).Applied))
}

// MarkApplied mocks base method.
func (m *MockPolicyVersionTracker) MarkApplied(version int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkApplied", version)
}

// MarkApplied indicates an expected call of MarkApplied.
func (mr *MockPolicyVersionTrackerMockRecorder) MarkApplied(version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkApplied", reflect.TypeOf((*MockPolicyVersionTracker)(nil).MarkApplied), version)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// EnforceObserved mocks base method.
func (m *MockMetrics) EnforceObserved(ctx context.Context, result, method, routeTemplate string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnforceObserved", ctx, result, method, routeTemplate, duration)
}

// EnforceObserved indicates an expected call of EnforceObserved.
func (mr *MockMetricsMockRecorder) EnforceObserved(ctx, result, method, routeTemplate, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceObserved", reflect.TypeOf((*MockMetrics)(nil).EnforceObserved), ctx, result, method, routeTemplate, duration)
}

// PolicyPublishFailed mocks base method.
func (m *MockMetrics) PolicyPublishFailed(ctx context.Context, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyPublishFailed", ctx, reason)
}

// PolicyPublishFailed indicates an expected call of PolicyPublishFailed.
func (mr *MockMetricsMockRecorder) PolicyPublishFailed(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyPublishFailed", reflect.TypeOf((*MockMetrics)(nil).PolicyPublishFailed), ctx, reason)
}

// PolicyPublishSucceeded mocks base method.
func (m *MockMetrics) PolicyPublishSucceeded(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyPublishSucceeded", ctx)
}

// PolicyPublishSucceeded indicates an expected call of PolicyPublishSucceeded.
func (mr *MockMetricsMockRecorder) PolicyPublishSucceeded(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyPublishSucceeded", reflect.TypeOf((*MockMetrics)(nil).PolicyPublishSucceeded), ctx)
}

// PolicyReloadFailed mocks base method.
func (m *MockMetrics) PolicyReloadFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadFailed", ctx, source, reason)
}

// PolicyReloadFailed indicates an expected call of PolicyReloadFailed.
func (mr *MockMetricsMockRecorder) PolicyReloadFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadFailed", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadFailed), ctx, source, reason)
}

// PolicyReloadSucceeded mocks base method.
func (m *MockMetrics) PolicyReloadSucceeded(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadSucceeded", ctx, source)
}

// PolicyReloadSucceeded indicates an expected call of PolicyReloadSucceeded.
func (mr *MockMetricsMockRecorder) PolicyReloadSucceeded(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadSucceeded", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadSucceeded), ctx, source)
}

// RouteDiffObserved mocks base method.
func (m *MockMetrics) RouteDiffObserved(ctx context.Context, missing, stale int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RouteDiffObserved", ctx, missing, stale)
}

// RouteDiffObserved indicates an expected call of RouteDiffObserved.
func (mr *MockMetricsMockRecorder) RouteDiffObserved(ctx, missing, stale any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RouteDiffObserved", reflect.TypeOf((*MockMetrics)(nil).RouteDiffObserved), ctx, missing, stale)
}

// WatcherCheckFailed mocks base method.
func (m *MockMetrics) WatcherCheckFailed(ctx context.Context, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherCheckFailed", ctx, reason)
}

// WatcherCheckFailed indicates an expected call of WatcherCheckFailed.
func (mr *MockMetricsMockRecorder) WatcherCheckFailed(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherCheckFailed", reflect.TypeOf((*MockMetrics)(nil).WatcherCheckFailed), ctx, reason)
}

// WatcherReloadFailed mocks base method.
func (m *MockMetrics) WatcherReloadFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherReloadFailed", ctx, source, reason)
}

// WatcherReloadFailed indicates an expected call of WatcherReloadFailed.
func (mr *MockMetricsMockRecorder) WatcherReloadFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherReloadFailed", reflect.TypeOf((*MockMetrics)(nil).WatcherReloadFailed), ctx, source, reason)
}

// WatcherReloadSucceeded mocks base method.
func (m *MockMetrics) WatcherReloadSucceeded(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherReloadSucceeded", ctx, source)
}

// WatcherReloadSucceeded indicates an expected call of WatcherReloadSucceeded.
func (mr *MockMetricsMockRecorder) WatcherReloadSucceeded(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherReloadSucceeded", reflect.TypeOf((*MockMetrics)(nil).WatcherReloadSucceeded), ctx, source)
}

// WatcherVersionMismatch mocks base method.
func (m *MockMetrics) WatcherVersionMismatch(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherVersionMismatch", ctx, source)
}

// WatcherVersionMismatch indicates an expected call of WatcherVersionMismatch.
func (mr *MockMetricsMockRecorder) WatcherVersionMismatch(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherVersionMismatch", reflect.TypeOf((*MockMetrics)(nil).WatcherVersionMismatch), ctx, source)
}
