package openapi

import (
	"testing"

	"github.com/stretchr/testify/require"
)

func TestRenderGoDocumentUsesRawStringLiteral(t *testing.T) {
	source, err := RenderGoDocument([]byte(`{"openapi":"3.0.3"}`), GoDocumentOptions{
		PackageName:  "docs",
		FunctionName: "ReadDoc",
		ConstName:    "docJSON",
		GeneratedBy:  "test generator",
	})
	require.NoError(t, err)

	text := string(source)
	for _, want := range []string{
		"// Code generated by test generator; DO NOT EDIT.",
		"package docs",
		"func ReadDoc() []byte",
		"const docJSON = `{\"openapi\":\"3.0.3\"}`",
	} {
		require.Contains(t, text, want)
	}
}

func TestRenderGoDocumentFallsBackToQuotedString(t *testing.T) {
	source, err := RenderGoDocument([]byte("{\"description\":\"value with ` backtick\"}"), GoDocumentOptions{PackageName: "docs"})
	require.NoError(t, err)

	text := string(source)
	require.NotContains(t, text, "const openAPIDocument = `")
	require.Contains(t, text, "const openAPIDocument = \"")
	require.Contains(t, text, "value with ` backtick")
}

func TestRenderGoDocumentRequiresPackageName(t *testing.T) {
	_, err := RenderGoDocument([]byte("{}"), GoDocumentOptions{})
	require.Error(t, err)
	require.Contains(t, err.Error(), "package name is required")
}
