package openapi

import (
	"encoding/json"
	"fmt"
	"strings"
)

const (
	defaultReadFunctionName = "ReadOpenAPI"
	defaultDocumentConst    = "openAPIDocument"
)

// RenderGoDocument 将 OpenAPI JSON 渲染为可被服务 docs 包编译的 Go 源码。
// 输入应为最终 OpenAPI JSON；生成文件包含一个读取函数和一个文档常量，不负责再次校验文档内容。
func RenderGoDocument(jsonData []byte, opts GoDocumentOptions) ([]byte, error) {
	if opts.PackageName == "" {
		return nil, fmt.Errorf("package name is required")
	}

	functionName := opts.FunctionName
	if functionName == "" {
		functionName = defaultReadFunctionName
	}
	constName := opts.ConstName
	if constName == "" {
		constName = defaultDocumentConst
	}
	generatedBy := opts.GeneratedBy
	if generatedBy == "" {
		generatedBy = "OpenAPI generator"
	}

	source := fmt.Sprintf(`// Code generated by %s; DO NOT EDIT.

package %s

// %s 返回生成的 OpenAPI 3 JSON 文档。
func %s() []byte {
	return []byte(%s)
}

const %s = %s
`, generatedBy, opts.PackageName, functionName, functionName, constName, constName, rawStringLiteral(string(jsonData)))

	return []byte(source), nil
}

func rawStringLiteral(value string) string {
	// 无反引号时使用 raw string literal 保持生成文件可读；含反引号时退回 JSON quoted string，json.Marshal(string) 失败属于不可恢复内部异常。
	if !strings.Contains(value, "`") {
		return "`" + value + "`"
	}

	quoted, err := json.Marshal(value)
	if err != nil {
		panic(err)
	}
	return string(quoted)
}
