// Code generated by ent, DO NOT EDIT.

package rbacpolicyrevisioncounter

import (
	"entgo.io/ent/dialect/sql"
	"github.com/aegiscore/user-service/internal/persistence/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldLTE(FieldID, id))
}

// LastRevision applies equality check predicate on the "last_revision" field. It's identical to LastRevisionEQ.
func LastRevision(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldEQ(FieldLastRevision, v))
}

// LastRevisionEQ applies the EQ predicate on the "last_revision" field.
func LastRevisionEQ(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldEQ(FieldLastRevision, v))
}

// LastRevisionNEQ applies the NEQ predicate on the "last_revision" field.
func LastRevisionNEQ(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldNEQ(FieldLastRevision, v))
}

// LastRevisionIn applies the In predicate on the "last_revision" field.
func LastRevisionIn(vs ...int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldIn(FieldLastRevision, vs...))
}

// LastRevisionNotIn applies the NotIn predicate on the "last_revision" field.
func LastRevisionNotIn(vs ...int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldNotIn(FieldLastRevision, vs...))
}

// LastRevisionGT applies the GT predicate on the "last_revision" field.
func LastRevisionGT(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldGT(FieldLastRevision, v))
}

// LastRevisionGTE applies the GTE predicate on the "last_revision" field.
func LastRevisionGTE(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldGTE(FieldLastRevision, v))
}

// LastRevisionLT applies the LT predicate on the "last_revision" field.
func LastRevisionLT(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldLT(FieldLastRevision, v))
}

// LastRevisionLTE applies the LTE predicate on the "last_revision" field.
func LastRevisionLTE(v int64) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.FieldLTE(FieldLastRevision, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RbacPolicyRevisionCounter) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RbacPolicyRevisionCounter) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RbacPolicyRevisionCounter) predicate.RbacPolicyRevisionCounter {
	return predicate.RbacPolicyRevisionCounter(sql.NotPredicates(p))
}
