package rbacbaseline

// DefaultPermissions 返回用户服务当前系统 RBAC 权限基线。
func DefaultPermissions() []PermissionSpec {
	return []PermissionSpec{
		{
			PermissionID: PermissionUserListID,
			Name:         "查询用户列表",
			Description:  "允许分页查询用户资料",
			Module:       "user",
			Method:       "GET",
			PathTemplate: "/api/v1/users",
		},
		{
			PermissionID: PermissionUserCreateID,
			Name:         "创建用户",
			Description:  "允许创建用户资料",
			Module:       "user",
			Method:       "POST",
			PathTemplate: "/api/v1/users",
		},
		{
			PermissionID: PermissionUserGetID,
			Name:         "查看用户详情",
			Description:  "允许按用户 ID 查询用户资料",
			Module:       "user",
			Method:       "GET",
			PathTemplate: "/api/v1/users/:user_id",
		},
		{
			PermissionID: PermissionPermissionListID,
			Name:         "查询权限列表",
			Description:  "允许分页查询权限目录",
			Module:       "permission",
			Method:       "GET",
			PathTemplate: "/api/v1/permissions",
		},
		{
			PermissionID: PermissionPermissionUserEffectiveID,
			Name:         "查询用户有效权限",
			Description:  "允许查询用户经角色绑定后当前生效的权限集合",
			Module:       "permission",
			Method:       "GET",
			PathTemplate: "/api/v1/permissions/users/:user_id/effective",
		},
		{
			PermissionID: PermissionRoleListID,
			Name:         "查询角色列表",
			Description:  "允许分页查询角色",
			Module:       "role",
			Method:       "GET",
			PathTemplate: "/api/v1/roles",
		},
		{
			PermissionID: PermissionRoleCreateID,
			Name:         "创建角色",
			Description:  "允许创建角色",
			Module:       "role",
			Method:       "POST",
			PathTemplate: "/api/v1/roles",
		},
		{
			PermissionID: PermissionRoleGetID,
			Name:         "查询角色详情",
			Description:  "允许按角色 ID 查询角色详情",
			Module:       "role",
			Method:       "GET",
			PathTemplate: "/api/v1/roles/:role_id",
		},
		{
			PermissionID: PermissionRoleUpdateID,
			Name:         "更新角色",
			Description:  "允许更新角色元数据",
			Module:       "role",
			Method:       "PATCH",
			PathTemplate: "/api/v1/roles/:role_id",
		},
		{
			PermissionID: PermissionRoleStatusID,
			Name:         "启停角色",
			Description:  "允许启用或停用角色",
			Module:       "role",
			Method:       "PATCH",
			PathTemplate: "/api/v1/roles/:role_id/status",
		},
		{
			PermissionID: PermissionUserRoleListID,
			Name:         "查询用户角色",
			Description:  "允许查询用户当前绑定的角色列表",
			Module:       "user-role",
			Method:       "GET",
			PathTemplate: "/api/v1/users/:user_id/roles",
		},
		{
			PermissionID: PermissionUserRoleReplaceID,
			Name:         "替换用户角色",
			Description:  "允许幂等替换用户完整角色集合",
			Module:       "user-role",
			Method:       "PUT",
			PathTemplate: "/api/v1/users/:user_id/roles",
		},
		{
			PermissionID: PermissionUserRoleAddID,
			Name:         "绑定用户角色",
			Description:  "允许为用户新增一个角色绑定",
			Module:       "user-role",
			Method:       "POST",
			PathTemplate: "/api/v1/users/:user_id/roles",
		},
		{
			PermissionID: PermissionUserRoleRemoveID,
			Name:         "解绑用户角色",
			Description:  "允许删除用户角色绑定",
			Module:       "user-role",
			Method:       "DELETE",
			PathTemplate: "/api/v1/users/:user_id/roles/:role_id",
		},
		{
			PermissionID: PermissionRolePermissionListID,
			Name:         "查询角色权限",
			Description:  "允许查询角色绑定的权限列表",
			Module:       "role-permission",
			Method:       "GET",
			PathTemplate: "/api/v1/roles/:role_id/permissions",
		},
		{
			PermissionID: PermissionRolePermissionReplaceID,
			Name:         "替换角色权限",
			Description:  "允许幂等替换角色完整权限集合",
			Module:       "role-permission",
			Method:       "PUT",
			PathTemplate: "/api/v1/roles/:role_id/permissions",
		},
		{
			PermissionID: PermissionRolePermissionAddID,
			Name:         "绑定角色权限",
			Description:  "允许为角色新增一个启用权限绑定",
			Module:       "role-permission",
			Method:       "POST",
			PathTemplate: "/api/v1/roles/:role_id/permissions",
		},
		{
			PermissionID: PermissionRolePermissionRemoveID,
			Name:         "解绑角色权限",
			Description:  "允许删除角色权限绑定",
			Module:       "role-permission",
			Method:       "DELETE",
			PathTemplate: "/api/v1/roles/:role_id/permissions/:permission_id",
		},
	}
}
