// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/aegiscore/user-service/internal/features/permission/application (interfaces: PolicyReloadEngine,Metrics)
//
// Generated by this command:
//
//	mockgen -destination=mock_policy_watcher_test.go -package=redis github.com/aegiscore/user-service/internal/features/permission/application PolicyReloadEngine,Metrics
//

// Package redis is a generated GoMock package.
package redis

import (
	context "context"
	reflect "reflect"
	time "time"

	application "github.com/aegiscore/user-service/internal/features/permission/application"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPolicyReloadEngine is a mock of PolicyReloadEngine interface.
type MockPolicyReloadEngine struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyReloadEngineMockRecorder
	isgomock struct{}
}

// MockPolicyReloadEngineMockRecorder is the mock recorder for MockPolicyReloadEngine.
type MockPolicyReloadEngineMockRecorder struct {
	mock *MockPolicyReloadEngine
}

// NewMockPolicyReloadEngine creates a new mock instance.
func NewMockPolicyReloadEngine(ctrl *gomock.Controller) *MockPolicyReloadEngine {
	mock := &MockPolicyReloadEngine{ctrl: ctrl}
	mock.recorder = &MockPolicyReloadEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyReloadEngine) EXPECT() *MockPolicyReloadEngineMockRecorder {
	return m.recorder
}

// AppliedRevision mocks base method.
func (m *MockPolicyReloadEngine) AppliedRevision() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AppliedRevision")
	ret0, _ := ret[0].(int64)
	return ret0
}

// AppliedRevision indicates an expected call of AppliedRevision.
func (mr *MockPolicyReloadEngineMockRecorder) AppliedRevision() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppliedRevision", reflect.TypeOf((*MockPolicyReloadEngine)(nil).AppliedRevision))
}

// InvalidateAllUserRoles mocks base method.
func (m *MockPolicyReloadEngine) InvalidateAllUserRoles() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateAllUserRoles")
}

// InvalidateAllUserRoles indicates an expected call of InvalidateAllUserRoles.
func (mr *MockPolicyReloadEngineMockRecorder) InvalidateAllUserRoles() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateAllUserRoles", reflect.TypeOf((*MockPolicyReloadEngine)(nil).InvalidateAllUserRoles))
}

// InvalidateUserRole mocks base method.
func (m *MockPolicyReloadEngine) InvalidateUserRole(userID uuid.UUID) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InvalidateUserRole", userID)
}

// InvalidateUserRole indicates an expected call of InvalidateUserRole.
func (mr *MockPolicyReloadEngineMockRecorder) InvalidateUserRole(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserRole", reflect.TypeOf((*MockPolicyReloadEngine)(nil).InvalidateUserRole), userID)
}

// ObserveTargetRevision mocks base method.
func (m *MockPolicyReloadEngine) ObserveTargetRevision(targetRevision int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveTargetRevision", targetRevision)
}

// ObserveTargetRevision indicates an expected call of ObserveTargetRevision.
func (mr *MockPolicyReloadEngineMockRecorder) ObserveTargetRevision(targetRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveTargetRevision", reflect.TypeOf((*MockPolicyReloadEngine)(nil).ObserveTargetRevision), targetRevision)
}

// ProjectionStatus mocks base method.
func (m *MockPolicyReloadEngine) ProjectionStatus() application.PolicyProjectionStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProjectionStatus")
	ret0, _ := ret[0].(application.PolicyProjectionStatus)
	return ret0
}

// ProjectionStatus indicates an expected call of ProjectionStatus.
func (mr *MockPolicyReloadEngineMockRecorder) ProjectionStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProjectionStatus", reflect.TypeOf((*MockPolicyReloadEngine)(nil).ProjectionStatus))
}

// RefreshToRevision mocks base method.
func (m *MockPolicyReloadEngine) RefreshToRevision(ctx context.Context, targetRevision int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToRevision", ctx, targetRevision)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToRevision indicates an expected call of RefreshToRevision.
func (mr *MockPolicyReloadEngineMockRecorder) RefreshToRevision(ctx, targetRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToRevision", reflect.TypeOf((*MockPolicyReloadEngine)(nil).RefreshToRevision), ctx, targetRevision)
}

// ReloadToRevision mocks base method.
func (m *MockPolicyReloadEngine) ReloadToRevision(ctx context.Context, targetRevision int64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReloadToRevision", ctx, targetRevision)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReloadToRevision indicates an expected call of ReloadToRevision.
func (mr *MockPolicyReloadEngineMockRecorder) ReloadToRevision(ctx, targetRevision any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReloadToRevision", reflect.TypeOf((*MockPolicyReloadEngine)(nil).ReloadToRevision), ctx, targetRevision)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// DispatcherBacklogObserved mocks base method.
func (m *MockMetrics) DispatcherBacklogObserved(ctx context.Context, dueCount int, oldestUnfinishedAge time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DispatcherBacklogObserved", ctx, dueCount, oldestUnfinishedAge)
}

// DispatcherBacklogObserved indicates an expected call of DispatcherBacklogObserved.
func (mr *MockMetricsMockRecorder) DispatcherBacklogObserved(ctx, dueCount, oldestUnfinishedAge any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatcherBacklogObserved", reflect.TypeOf((*MockMetrics)(nil).DispatcherBacklogObserved), ctx, dueCount, oldestUnfinishedAge)
}

// DispatcherOperationObserved mocks base method.
func (m *MockMetrics) DispatcherOperationObserved(ctx context.Context, operation, result, reason, kind string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DispatcherOperationObserved", ctx, operation, result, reason, kind)
}

// DispatcherOperationObserved indicates an expected call of DispatcherOperationObserved.
func (mr *MockMetricsMockRecorder) DispatcherOperationObserved(ctx, operation, result, reason, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatcherOperationObserved", reflect.TypeOf((*MockMetrics)(nil).DispatcherOperationObserved), ctx, operation, result, reason, kind)
}

// DispatcherRunningObserved mocks base method.
func (m *MockMetrics) DispatcherRunningObserved(ctx context.Context, running bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DispatcherRunningObserved", ctx, running)
}

// DispatcherRunningObserved indicates an expected call of DispatcherRunningObserved.
func (mr *MockMetricsMockRecorder) DispatcherRunningObserved(ctx, running any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DispatcherRunningObserved", reflect.TypeOf((*MockMetrics)(nil).DispatcherRunningObserved), ctx, running)
}

// EnforceObserved mocks base method.
func (m *MockMetrics) EnforceObserved(ctx context.Context, result, method, routeTemplate string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnforceObserved", ctx, result, method, routeTemplate, duration)
}

// EnforceObserved indicates an expected call of EnforceObserved.
func (mr *MockMetricsMockRecorder) EnforceObserved(ctx, result, method, routeTemplate, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnforceObserved", reflect.TypeOf((*MockMetrics)(nil).EnforceObserved), ctx, result, method, routeTemplate, duration)
}

// PolicyPublishFailed mocks base method.
func (m *MockMetrics) PolicyPublishFailed(ctx context.Context, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyPublishFailed", ctx, reason)
}

// PolicyPublishFailed indicates an expected call of PolicyPublishFailed.
func (mr *MockMetricsMockRecorder) PolicyPublishFailed(ctx, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyPublishFailed", reflect.TypeOf((*MockMetrics)(nil).PolicyPublishFailed), ctx, reason)
}

// PolicyPublishSucceeded mocks base method.
func (m *MockMetrics) PolicyPublishSucceeded(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyPublishSucceeded", ctx)
}

// PolicyPublishSucceeded indicates an expected call of PolicyPublishSucceeded.
func (mr *MockMetricsMockRecorder) PolicyPublishSucceeded(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyPublishSucceeded", reflect.TypeOf((*MockMetrics)(nil).PolicyPublishSucceeded), ctx)
}

// PolicyReloadFailed mocks base method.
func (m *MockMetrics) PolicyReloadFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadFailed", ctx, source, reason)
}

// PolicyReloadFailed indicates an expected call of PolicyReloadFailed.
func (mr *MockMetricsMockRecorder) PolicyReloadFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadFailed", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadFailed), ctx, source, reason)
}

// PolicyReloadLagObserved mocks base method.
func (m *MockMetrics) PolicyReloadLagObserved(ctx context.Context, lag int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadLagObserved", ctx, lag)
}

// PolicyReloadLagObserved indicates an expected call of PolicyReloadLagObserved.
func (mr *MockMetricsMockRecorder) PolicyReloadLagObserved(ctx, lag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadLagObserved", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadLagObserved), ctx, lag)
}

// PolicyReloadSucceeded mocks base method.
func (m *MockMetrics) PolicyReloadSucceeded(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PolicyReloadSucceeded", ctx, source)
}

// PolicyReloadSucceeded indicates an expected call of PolicyReloadSucceeded.
func (mr *MockMetricsMockRecorder) PolicyReloadSucceeded(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PolicyReloadSucceeded", reflect.TypeOf((*MockMetrics)(nil).PolicyReloadSucceeded), ctx, source)
}

// WatcherCheckFailed mocks base method.
func (m *MockMetrics) WatcherCheckFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherCheckFailed", ctx, source, reason)
}

// WatcherCheckFailed indicates an expected call of WatcherCheckFailed.
func (mr *MockMetricsMockRecorder) WatcherCheckFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherCheckFailed", reflect.TypeOf((*MockMetrics)(nil).WatcherCheckFailed), ctx, source, reason)
}

// WatcherReloadFailed mocks base method.
func (m *MockMetrics) WatcherReloadFailed(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherReloadFailed", ctx, source, reason)
}

// WatcherReloadFailed indicates an expected call of WatcherReloadFailed.
func (mr *MockMetricsMockRecorder) WatcherReloadFailed(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherReloadFailed", reflect.TypeOf((*MockMetrics)(nil).WatcherReloadFailed), ctx, source, reason)
}

// WatcherReloadSucceeded mocks base method.
func (m *MockMetrics) WatcherReloadSucceeded(ctx context.Context, source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherReloadSucceeded", ctx, source)
}

// WatcherReloadSucceeded indicates an expected call of WatcherReloadSucceeded.
func (mr *MockMetricsMockRecorder) WatcherReloadSucceeded(ctx, source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherReloadSucceeded", reflect.TypeOf((*MockMetrics)(nil).WatcherReloadSucceeded), ctx, source)
}

// WatcherVersionMismatch mocks base method.
func (m *MockMetrics) WatcherVersionMismatch(ctx context.Context, source, reason string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "WatcherVersionMismatch", ctx, source, reason)
}

// WatcherVersionMismatch indicates an expected call of WatcherVersionMismatch.
func (mr *MockMetricsMockRecorder) WatcherVersionMismatch(ctx, source, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatcherVersionMismatch", reflect.TypeOf((*MockMetrics)(nil).WatcherVersionMismatch), ctx, source, reason)
}
